### ISSUE TITLE
Incorrect fuzzy match on h. blog

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2798] opened 2015-12-14 16:15 UTC
On this blog post:
https://hypothes.is/blog/the-lit-anthology-in-the-age-of-web-annotation/

There is one annotation: https://hypothes.is/a/AVGM5F1W8sFu_DXLVN2W
And it's context: http://h.jonudell.info:8080/annos_for_url?url=https%3A%2F%2Fhypothes.is%2Fblog%2Fthe-lit-anthology-in-the-age-of-web-annotation%2F

The annotation is a copy edit, selecting the word "Robin" and suggesting that it should be "Elisa".  @jeremydean then made the correction suggested in the annotaiton, changing Robin to Elisa.  The algorithm now anchors the annotation to a previous instance of "Robin" in the same sentence, instead of orphaning the annotation.

**Comment by nickstenning** [comment] 2016-02-10 15:04
This annotation has now been deleted, so we can't reproduce/analyse whether this was a bug or not. Closing.

**Closed by nickstenning** 2016-02-10 15:04 UTC
