### ISSUE TITLE
Highlight disappears after clicking adder icon

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1992] opened 2015-03-04 15:16 UTC
At least not until you focus on that card in the sidebar.

In the intervening time it looks like something broke--as your select text disappears.

New annotations should probably have their highlights stay on the page--with or without hover.

Or better yet, "Show Annotations" (at least mine) should be on when I'm annotating...

**Comment by csillag** [comment] 2015-03-06 14:11
We used to have a class called `annotation-hl-temporary`, which had exectly this rule.
(It decorated the HL of the annotation that was currently being created.)

Later it was removed, but I don't remember whether or not that was a conscious decision or not, and if it was, what was the rationale.

Anyway, I agree with the proposal in the OP. We should bring it back.

**Comment by tilgovi** [comment] 2015-03-06 18:40
The decision was conscious. It was made my be. The styling was no different than a regular highlight, so I just let that be the rule.

**Comment by BigBlueHat** [comment] 2015-03-06 20:21
The problem isn't that they matched, but that the non-temporary one doesn't
show up soon enough--and we need something there as a place holder (or make
the real in-progress highlight stay around some other way) while the person
makes their changes.

Lots of ways to come at this (as ever). No preference (here) on how it's
fixed.

**Comment by csillag** [comment] 2015-03-24 02:31
So @tilgovi, would you be OK with using the default style for regular highlights for the annotation that is currently being created?

**Comment by tilgovi** [comment] 2015-03-24 03:24
Sounds reasonable. But there may be some trickiness around selection color and making sure that we both a) show the new highlight the same as existing ones and b) still make it possible to see your overlap selections. Might be a matter of making sure we deselect on adder click?

**Comment by csillag** [comment] 2015-03-24 09:30
> there may be some trickiness around selection color and making sure that we both
> a) show the new highlight the same as existing ones and
> b) still make it possible to see your overlap selections.
>
> Might be a matter of making sure we deselect on adder click?

I'm not sure I fully understand the concern here. We [deselect](https://github.com/hypothesis/h/blob/25efdd689f7d7008bf1f5f3e4ef1bbba2576ef01/h/static/scripts/guest.coffee#L402) on adder click.
Fwiw, I'll just add a separate CSS class for now, making it easier to tweak the style later.

**Comment by RawKStar77** [comment] 2015-06-04 18:22
More discussion relevant to this issue was had here: https://github.com/hypothesis/h/pull/2264

I  think a way to solve this issue is to modify how the set visibility conrtol works so that highlights that I make are always visible, highlights that others make are toggled by the control.

This would solve this issue. 

@judell commented on #2264:

> When I was co-editing a document with Maryann and Dan last week I often toggled between no highlights, so I could read without disruption, and highlights to co-edit. If I'm annotating a public page I might want the same kind of experience, or might prefer to see only mine.

I think this gets to the heart of the value for the set visibility control: some people strongly prefer to read something once through without distractions. I think to avoid weird states like the one talked about in this current issue, modifying the visibility control so that my highlights are always visible, but I have the option to easily hide the highlights of others and have a much less yellow reading experience.

**Comment by judell** [comment] 2015-06-04 18:43
"a user's personal annotations/highlights are always visible,"

I don't want even my own annotations always visible. I often want to read without any distractions at all. I really value the off switch.

**Comment by dwhly** [comment] 2015-06-05 01:38
> I don't want even my own annotations always visible. I often want to read without any distractions at all. I really value the off switch.

Yes.

**Comment by RawKStar77** [comment] 2015-06-08 18:00
Getting back to the issue at hand here, the problem is that when visible highlights are not set, when I make an annotation I don't see a highlight. *Is this a problem?*

It seems like none of the proposed 'solutions' to this problem have been quite satisfactory, so is it helpful to leave this open?

**Comment by tilgovi** [comment] 2015-06-08 19:56
Definitely helpful to leave this open.

**Comment by nickstenning** [comment] 2016-02-10 12:57
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Closed by nickstenning** 2016-02-10 12:57 UTC
Labels: Usability
