### ISSUE TITLE
App freezes on docs.meteor.com

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2040] opened 2015-03-14 15:01 UTC
Go here, the page freezes (have to forcibly kill the tab).
via.hypothes.is/h/docs.meteor.com/#/basic/

Here's the console:
Creating Application Cache with manifest https://via.hypothes.is/app.manifest
(index):1 Application Cache Checking event
(index):1 Application Cache Error event: Manifest fetch failed (404) https://via.hypothes.is/app.manifest
33499dc194228cefcb2ad1687d4ce8b34376cd38.js:73 Mixed Content: The page at 'https://via.hypothes.is/h/http://docs.meteor.com/#/basic/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://docs.meteor.com/sockjs/625/5bz23dui/websocket'. This request has been blocked; this endpoint must be available over WSS.
33499dc194228cefcb2ad1687d4ce8b34376cd38.js:73 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by csillag** [comment] 2015-03-14 17:33
All that you see on the console comes from their app, not ours.
Anyway, I suspect the problem to be the same as in #2016.

Given that we have bumped into this problem twice within a week, and both on high-traffic pages, I am inclined to give this some priority, and to try to solve it ASAP. (Unless, of course, if these pages depend on the full set of dynamic support features.)

**Comment by Treora** [comment] 2015-03-15 19:19
I noticed the same problem (when reading docs.meteor.com) some weeks ago and opened #1893, which was then marked a duplicate of https://github.com/hypothesis/dom-text-mapper/issues/45 .

**Comment by tilgovi** [comment] 2015-03-15 20:33
This is completely separate but horrifying:

    Creating Application Cache with manifest https://via.hypothes.is/app.manifest

**Comment by tilgovi** [comment] 2015-03-15 20:34
We need via to strip appcache manifests or we might wind up in a situation where some pages fetched by via are cached in the browser _forever_ in such a way that they might even make other pages inaccessible.

**Comment by tilgovi** [comment] 2015-03-15 20:35
Never mind. That may not be a problem.

**Comment by tilgovi** [comment] 2015-03-15 20:40
Actually, opened hypothesis/via#7 to discuss.

**Comment by tilgovi** [comment] 2015-03-15 20:40
Doesn't kill my tab, just freezes for a few seconds. Closing again as duplicate of hypothesis/dom-text-mapper#45.

**Closed by tilgovi** 2015-03-15 20:40 UTC
Labels: Bug, Site Report
