### ISSUE TITLE
User experience when account activation email is lost?

### ISSUE THREAD

**Issue by edrex** [hypothesis/h#2988] opened 2016-02-20 06:41 UTC
I have a friend who signed up a few months back but never activated their account. 

Trying to sign in now, they see the message:

 "You haven't activated your account. Check your email..."

but they can't locate the activation email.

Until the user has verified ownership of the account email address, it really ought to be possible for someone else claim it.

Alternatively (less ideal IMO since it doesn't prevent DOS by falsely claiming an address) users could be allowed to trigger resending the activation email, when the error message above is shown.

**Comment by robertknight** [comment] 2016-02-20 07:33
Related Trello card, which suggests that the emails send by the "Forgot password" link should also activate the account if necessary, since it provides the same proof of email ownership - https://trello.com/c/FQY6SYjt/485-forgot-password-emails-should-also-activate-account

That card is on a Trello board internal to H, so I'll reproduce it here:

> This morning I encountered several support emails from users who had not seen
> their account activation emails. When logging in to Hypothesis they had tried to
> use the "Forgot password" link instead.
> Since the "Forgot password" emails also provide proof of email ownership, I propose
> that clicking the link in these emails should also verify the user's email address.

**Comment by robertknight** [comment] 2016-02-20 07:36
We're also looking into reworking the activation process entirely, so you can start using H without having to activate your email but with some limitations and an obvious way to re-send the activation email if necessary.

We'll also be looking into social logins (major ones such as Google and more domain-specific ones as well) in future.

**Comment by edrex** [comment] 2016-02-22 18:25
Allowing password reset tokens to perform account activation seem like an economical way to deal with lost activation tokens.

There are several places where the auth system might offer to generate a token; it's important the messaging makes sense in context/

 - Sign in form ("[Forgot password]")
 - Register form, when email address already exists in the system
   - If account email is verified: "[Sign in] or [Forgot password]"
   - If account email is unverified: "An account already exists with that email but hasn't been activated. [Resend activation email]"

Some dissonance would result if a user tries to register with an identity for which an imposter has already created an (unverified) account, as they would end up with the account data from the imposter. This seems low-risk however, since as long as the identity associated with the email isn't exposed to third parties (pre-verification) there isn't much incentive to impersonation.

Questions:
 - Would cashing in the dual-purpose token require resetting the password? I think it should, since the user redeeming the token may not be the user who created the account initially, and the lost token scenario is fairly uncommon. 
 - Would the initial activation token require resetting the password? I guess no, since this is the "happy path". So two kinds of tokens.

Making auth systems is complicated and boring. Why not use something off the shelf?

**Comment by nickstenning** [comment] 2016-04-20 01:11
Hi Ed, thanks for filing this issue. The situation now is that reset password emails can be used to activate accounts. We'll continue to evaluate how we can improve the situation in future, including considering making it possible to re-send activation emails.

I'm going to close this issue both because we've made some progress here but also because we don't use GitHub to track mooted improvements, but solely for bugs and issues.

**Closed by nickstenning** 2016-04-20 01:11 UTC
