### ISSUE TITLE
Annotating MailChimp newsletter preview post kills Firefox

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1983] opened 2015-02-26 16:19 UTC
For example:
http://us2.campaign-archive2.com/?u=8e541b1767522351f98c47124&id=c0d2d9158f&e=

Tested with the bookmarklet in Firefox 36 on Mac (got the spinning beach ball of death) and Firefox 35 on Windows (got a Stop Script or Debug) message.

Debugger pointed to DomTextMapper as where things were stalled.

**Comment by csillag** [comment] 2015-02-26 16:30
Looks like this page triggers this bug:
https://github.com/hypothesis/dom-text-mapper/issues/12

It's great to have a way to reliably reproduce it.

**Comment by csillag** [comment] 2015-02-26 16:47
Closed by https://github.com/hypothesis/h/commit/daacc5cf8ee3a901c07e63128aba1e11be5c984c.

**Closed by csillag** 2015-02-26 16:47 UTC
Labels: Site Report
