### ISSUE TITLE
"message not available" on stream

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3393] opened 2016-05-31 22:22 UTC
https://hypothes.is/api/annotations/_95k5iddEea9_PNBWHea7w resolves to a public annotation.

https://hypothes.is/a/_95k5iddEea9_PNBWHea7w reports "message not available"

**Comment by nickstenning** [comment] 2016-06-01 11:50
Closing as a duplicate of #3367.

**Closed by nickstenning** 2016-06-01 11:50 UTC
