### ISSUE TITLE
Adder doesn't show properly on ESPN.com

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3192] opened 2016-04-08 21:49 UTC
### Steps to reproduce
1. With Chrome extension
2. Go here: http://espn.go.com/nba/story/_/id/15159766/golden-state-warriors-coach-steve-kerr-inclined-rest-players-talk-team-first
   3 Make a selection
### Expected behaviour

Adder should show
### Actual behaviour

It doesn't
### Additional details

Luckily since the page note feature is now responsive to selections, you can click the icon and still create an annotation on the selection regardless.  But we should fix the adder problem if possible.

**Comment by nickstenning** [comment] 2016-04-11 12:51
Had a quick look into this and the problem is that the page declares a huge z-index on the main body container element:

```CSS
#global-viewport #pane-main {
    background: #f1f2f3;
    position: relative;
    width: 100%;
    z-index: 1000006;
}
```

I'm going to close this as a duplicate of that issue.

**Comment by klemay** [comment] 2018-10-29 17:11
This does not seem to have fixed the problem - [another report of the adder not showing](https://hypothesis.zendesk.com/agent/tickets/3267) came in today, and I am able to replicate.

This time the user was trying to annotate: http://www.espn.com/mlb/story/_/id/25114132/mlb-how-stars-unexpected-heroes-made-boston-red-sox-unstoppable

**Comment by klemay** [comment] 2018-10-29 17:18
In the meantime, as Dan points out above, the page note button can be used when text is highlighted to create annotations:

![annotate-espn](https://user-images.githubusercontent.com/12087705/47667708-0e2c9d80-db7d-11e8-98fe-c6ff51116dbf.png)

**Comment by klemay** [comment] 2020-11-09 20:20
The adder does appear, but the CSS is off (as of Nov 2020)

**Comment by klemay** [comment] 2020-11-11 16:52
closing in favor of https://github.com/hypothesis/browser-extension/issues/435

**Closed by klemay** 2020-11-11 16:52 UTC
Labels: design
