### ISSUE TITLE
document fields missing from API results

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3594] opened 2016-07-11 20:19 UTC
Can we please put back the link, highwire, and dc fields?

An archived result for https://hypothes.is/api/annotations/AVMv0vonH9ZO4OKSk_Ia:

```
		"document": {
			"twitter": {
                       ...snip...
			},
			"favicon": ["http://www.ncbi.nlm.nih.gov/favicon.ico"],
			"facebook": {
                        ...snip...
			},
			"link": [{
				"rel": "alternate",
				"href": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/epub/",
				"type": "application/epub+zip"
			}, {
				"href": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/"
			}, {
				"rel": "canonical",
				"href": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/"
			}, {
				"href": "doi:10.1186/s13036-015-0022-z"
			}, {
				"href": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/"
			}, {
				"rel": "alternate",
				"href": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/pdf/13036_2015_Article_22.pdf",
				"type": "application/pdf"
			}],
			"highwire": {
                        ...snip...
			},
			"title": ["Heterologous expression of the isopimaric acid pathway in Nicotiana benthamiana and the effect of N-terminal modifications of the involved cytochrome P450 enzyme"],
			"dc": {
                        ...snip...
			}
		},
```
Current result: 

```
	"document": {
		"title": ["Heterologous expression of the isopimaric acid pathway in Nicotiana benthamiana and the effect of N-terminal modifications of the involved cytochrome P450 enzyme"]
	},
```

**Comment by nickstenning** [comment] 2016-07-11 20:41
> Can we please put back the link, highwire, and dc fields?

Not immediately, no. What we've gained in integrity and flexibility with moving annotations into a normalised data store we have temporarily paid for in performance. In time, it will be perfectly possible to generate denormalised metadata like this for documents and cache it, but for now generating the full `document` object is a relatively slow process, so we can't do it in-request. The main reason for this is that the `document` property on an annotation would now be the correct, current document object, which can be *much* larger and more complicated than the typical document object submitted with annotations when they're created, to the extent that rendering out the JSON for the number of annotations in a search request becomes unacceptably slow.

If you gave us an idea of why or how this information was useful to you it might help us understand:

1. How/where to prioritise restoring access to this information via the API.
2. If there is a useful subset of the information which could be exposed through the API more quickly.
3. If there are any other ways of exposing this information (via a different API call, for example) that would satisfy your use cases.

In the mean time this isn't a bug -- it's intended behaviour -- so I'm going to close this issue. We can carry on the conversation about what you need here as part of our regular planning process.

**Closed by nickstenning** 2016-07-11 20:41 UTC

**Comment by judell** [comment] 2016-07-11 22:23
Fair enough. This turned out to be a distraction, the main issue being https://github.com/hypothesis/h/issues/3595. 

It would be nice to have a separate API to inspect equivalences, but for now I can parse out the same info as the client does (e.g. dc:identifier, citation_doi) and assume those were honored if found when annotating.
