### ISSUE TITLE
indicate when app is ready to respond

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2207] opened 2015-05-01 17:06 UTC
I just activated Hypothesis on [45 sites](https://hypothes.is/stream?q=user:judell&tag=hypothesis-in-the-press) in rapid succession. The chevron always appears quickly, and signals that the app is ready to respond, but the app doesn't actually become responsive for a while. The delay is unpredictable and varies widely. 

Until we are sufficiently fast and unobtrusive to remain always active, we should provide a clear indication that the app is ready to respond.

Straw man proposals:

- A spinner instead of the chevron/eye/note trio, until we are ready

- Grey the chevron/eye/note trio until we are ready

I care less about how, only that, we implement this. We should not always need it, but for now we do.

**Comment by csillag** [comment] 2015-05-01 21:20
I remember submitting an issue about this, but I can't find it now.

**Comment by judell** [comment] 2015-05-11 22:01
Thank you!

**Comment by csillag** [comment] 2015-05-11 22:02
Btw, this was a duplicate of #1977

**Comment by tilgovi** [comment] 2015-05-11 22:13
I think you accidentally closed this? The PR is still open.

**Comment by judell** [comment] 2015-05-11 23:13
I did. Must have been swept up in the excitement of all of today's closings!

**Closed** 2015-05-13 12:50 UTC
Labels: Needs Design
