### ISSUE TITLE
Condense quoted text in sidebar comments [UX]

### ISSUE THREAD

**Issue by bnvk** [hypothesis/h#2293] opened 2015-06-06 15:04 UTC
On pages with multiple comments by multiple authors, things can get a bit hairy in terms the eye visually parsing what content is what. I think a big reason for this is how many "variable" text fragments there are. The most interesting & relevant part of the sidebar IMHO is the comments written *by* people, not simply reshowing fragments of the article. I suggest putting a 2 line limiter on long text like this:

![screen shot 2015-06-06 at 4 44 20 pm](https://cloud.githubusercontent.com/assets/48677/8020109/5edb9b42-0c6d-11e5-9e30-7b6af925fb39.png)

So that it shows like this instead:

![hypothesis suggestions - collapsed quoted](https://cloud.githubusercontent.com/assets/48677/8020111/63789038-0c6d-11e5-9ff6-7fa367d2eeeb.png)

I think that draws much more attention to the comments written by Hypothesis users!

**Comment by dwhly** [comment] 2015-06-06 15:42
Completely agree.  https://github.com/hypothesis/h/issues/487

**Comment by tilgovi** [comment] 2015-06-10 17:42
Closing as duplicate of #487, which describes nearly an identical thing.

"I suggest putting a 2 line limiter on long text"

and

"Quotes, when bodies are uncollapsed, should be truncated to approximately two lines"

**Closed by tilgovi** 2015-06-10 17:42 UTC
