### ISSUE TITLE
Losing highlights after a large number in the same paragraph

### ISSUE THREAD

**Issue by saracarl** [hypothesis/h#4039] opened 2016-11-09 19:07 UTC
### Steps to reproduce
1.  open http://discovery.civilwargovernors.org/document/KYR-0001-004-1355 with hypothesis
2.  highlight entities (names & places) in order as seen (down column 1 before over to column 2) 
Result should be along these lines:
![1355dropping](https://cloud.githubusercontent.com/assets/708566/20150549/2c40e110-a67c-11e6-8570-f9b1229948fd.png)
(except w/o this bug all entities would be highlighted).  

### Expected behaviour
All previously highlighted entities/strings should remain highlighted.

### Actual behaviour
Around highlight 11 in the list of petitioners the previous highlight will be dropped.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

Version 42.0.2311.90 (64-bit)
(and likely others -- it's been reproduced on 2 other environments)

### Additional details
I'm working with the Kentucky Historical Society on a grad-student driven entity recognition project that uses Hypothesis to highlight (but not annotate) entities.

On pages with a lot of entities Hypothesis seems to drop entities when you hit something around 15 entities total or possibly ~10ish entites (this is not consistent) in a paragraph.
What I've seen is that it only drops one at a given time (which is when you are highlighting and saving another).  For example When you highlight the 11th, highlight #10 is dropped.  

We can "reset" the behavior by either scrolling the browser window (which moves the annotation count numbers on the right around) or by adding an actual annotation instead of a highlight (which seems to also move the browser window around).  When you "reset" you can do another run of 10 annotations in the same paragraph before it starts happening again.

This is a page that is the easiest to reproduce the issue -- the big run of names at the bottom is what does it:  http://discovery.civilwargovernors.org/document/KYR-0001-004-1355
I highlighted the leading paragraphs first with no problem, and then I *think* it dropped Paxton (#10 in the petition list) when I highlighted Floessfield (#11), as well as dropping more later on.  

I also reproduced it on this page:  http://discovery.civilwargovernors.org/document/KYR-0001-003-0068
I only highlighted the list of petitioners at the end, starting with the left hand column and moving to the right, and it dropped highlight #22 when I highlighted #23, as shown in the screenshot below:

![0068dropped22](https://cloud.githubusercontent.com/assets/708566/20150694/c942d73e-a67c-11e6-95c9-a737bb7b61fd.png)

I'm also seeing a possibly-related issue with highlight counts -- even though I only have 14 highlights, I'm seeing "6" and "9" and they have one overlapping entitity/highlight when I hover over them.

![6hypohighlights](https://cloud.githubusercontent.com/assets/708566/20150696/c943a2ae-a67c-11e6-9ddb-68671e4dfdf9.png)

![9hypohighlights](https://cloud.githubusercontent.com/assets/708566/20150693/c93ec162-a67c-11e6-8d5b-6ed6d22b30de.png)

(Note that GB Long is highlighted in both counts.)

**Comment by sheetaluk** [comment] 2016-11-15 12:22
Someone else is facing a similar issue:
https://hypothesis.zendesk.com/agent/tickets/776

**Comment by hoffm386** [comment] 2017-01-11 23:04
I'm encountering the same issue but the "reset" options listed above don't all work for me.  If I scroll on the page, or even refresh the browser window, that doesn't fix anything.  The only thing that seems to work is if I add an annotation.

One time when this happened, I got a JavaScript console error that says:

`Uncaught (in promise) TypeError: Cannot read property 'nodeValue' of null`
`at BrowserRange.Range.BrowserRange.BrowserRange.normalize (range.coffee:198)`
`at guest.coffee:219`
`at guest.coffee:19`

But this doesn't happen consistently

**Comment by hoffm386** [comment] 2017-01-11 23:23
I am also getting this error from pdf.js every time I load the page.  Their solution is to disable browser security settings which is not an acceptable answer.  Maybe someone more familiar with the code can discern whether this is likely to be related to the limitation on highlighting lots of entities in a row.

https://github.com/mozilla/pdf.js/issues/3150

**Comment by robertknight** [comment] 2017-01-12 10:02
I believe the problem here is related to the way that we currently draw highlights. Roughly speaking, what happens when loading a page is:

1. Hypothesis fetches annotations and locates the relevant parts of the page for each annotation (generating a `Range` to represent this location)
2. Hypothesis _modifies_ the page in order to insert the highlights

The problem is that in the process of inserting the highlight for one annotation, it can break the `Range` for another annotation found in step 1. Hence if you have a block of text with multiple overlapping highlights, some may fail to be shown.

> One time when this happened, I got a JavaScript console error that says:

This looks familiar. I've been able to generate a similar error when the text selection meets certain criteria in terms of exactly where it starts and ends in the document's tree structure.

> Maybe someone more familiar with the code can discern whether this is likely to be related to the limitation on highlighting lots of entities in a row

Can you post the URL of the PDF you are trying to annotate?

I don't think this is related. It looks purely like an issue with the way that PDF.js tries to detect whether it can progressively load the PDF - that is, start showing content before the entire file has been downloaded. PDF.js is trying to check if the server supports fetching parts of the file ("ranges") at a time but the server's response doesn't allow JavaScript to check for this.

**Comment by nickstenning** [comment] 2017-02-22 12:20
This has been fixed in https://github.com/hypothesis/client/issues/234 and released in Hypothesis v0.58.

**Closed by nickstenning** 2017-02-22 12:20 UTC
