### ISSUE TITLE
Annotations showing up as orphaned on pages with similar URLs

### ISSUE THREAD

**Issue by segdeha** [hypothesis/h#4456] opened 2017-03-29 22:31 UTC
### Steps to reproduce
1. Go to the following pages: https://blah-htuguhgrqn.now.sh/mod/oucontent/view.php?id=255382 https://blah-htuguhgrqn.now.sh/mod/oucontent/view.php?id=255382&section=1.2 https://blah-htuguhgrqn.now.sh/mod/oucontent/view.php?id=255382&section=1.3 (note, this is an ngrokified server set up by @sean-roberts, so if the URLs aren't working, let him know)
2. Annotate on any one of them, then reload the others
3. Notice there are orphaned annotations from the other pages

### Expected behaviour
Annotations should be scoped to the page on which they are made.

### Actual behaviour
Annotations made on the same page anchor successfully. Annotations made on any one page show up as orphaned on the others.

### Browser/system information
The issue was first reported by a user using Firefox, but @sean-roberts and I confirmed that it's also happening on Chrome. IOW, it doesn't seem to be dependent on the browser.

### Additional details
@sean-roberts’ initial speculation is that it could have to do with URL normalization, which I assume happens on the backend, which is why I am filing this under `h` :-)

**Comment by nickstenning** [comment] 2017-03-31 12:54
Summarising a conversation we had yesterday after standup:

This is happening because each page contains the following HTML tag, identical on each page:

```html
<link rel="alternate" type="application/rdf+xml" title="Empire of the microbes: Chapter 1" href="https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&amp;format=rdf" />
```

These tags are parsed as "claims of URI equivalence", and are stored in the database:

```
>>> document_uris = session.query(m.DocumentURI).filter_by(uri=u'https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&format=rdf').all()
>>> for du in document_uris:
...     print('claimant={} uri={} type={} content_type={}'.format(du.claimant, du.uri, du.type, du.content_type))
...
claimant=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382 uri=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&format=rdf type=rel-alternate content_type=application/rdf+xml
claimant=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&section=1.2 uri=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&format=rdf type=rel-alternate content_type=application/rdf+xml
claimant=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&section=1.3 uri=https://learn2.open.ac.uk/mod/oucontent/view.php?id=255382&format=rdf type=rel-alternate content_type=application/rdf+xml
...
```

At the moment, the code treats all such "claims" the same (with the [sole exception of `rel="canonical"` links](https://github.com/hypothesis/h/blob/ea6282184b9ff29b11a61817a7124d594484bfa2/h/storage.py#L237-L243)), so the three "claimants" (i.e. the three URLs which contain this tag) are deemed equivalent.

**Comment by jeremydean** [comment] 2017-04-06 12:37
With Nick's help have identified another site where this issue comes up as per this thread in lounge:

https://hypothes-is.slack.com/archives/C03QZM0K4/p1491444897001414

**Comment by chdorner** [comment] 2017-05-22 09:29
So it's clear what the bug is. But do we know what the intended behaviour should be? Do we need a list of link tags that we use for document equivalence, and others that we don't and potentially not even save these ones?

**Comment by klemay** [comment] 2018-02-21 17:41
See also: https://hypothesis.zendesk.com/agent/tickets/2184

**Comment by klemay** [comment] 2020-11-09 20:14
closing - in all of these examples, annotations anchor properly

**Closed by klemay** 2020-11-09 20:14 UTC
Labels: API, P3: Next sprint
