### ISSUE TITLE
Cards aren't visually truncated

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#487] opened 2013-07-10 02:24 UTC
We used to have this sorted out earlier.

1. Select a longer piece of text. (Several paragraphs.)
2. Make an annotation about it.
3. When the annotation is displayed, the whole quote is shown. 

With texts above a given length, we should only show a smaller part, with a small link or button to show the whole text.

- [ ] Quotes, when bodies are uncollapsed, should be truncated to approximately two lines (around 160 characters on avg) of text.  When bodies are collapsed, quotes should not be shown.
- [ ] Bodies, when annotations are collapsed, should be truncated to one line.  When bodies are uncollapsed should be shown in full.
- [ ] Truncation should result in ellipses "... " shown at the end of lines via CSS.  Clicking the ellipses should expose the remainder of the truncated text.

**Comment by bnvk** [comment] 2015-06-10 20:44
Adding my screenshots (for visual reference) as #2293 was closed in duplicate of this thread!

I suggest putting a 2 line limiter on long text like this:

![screen shot 2015-06-06 at 4 44 20 pm](https://cloud.githubusercontent.com/assets/48677/8020109/5edb9b42-0c6d-11e5-9e30-7b6af925fb39.png)

So that it shows like this instead:

![hypothesis suggestions - collapsed quoted](https://cloud.githubusercontent.com/assets/48677/8020111/63789038-0c6d-11e5-9ff6-7fa367d2eeeb.png)

I think that draws much more attention to the comments written by Hypothesis users!

**Comment by nickstenning** [comment] 2016-02-10 12:43
This is now done: #2451, #2802, #2894.

**Closed by nickstenning** 2016-02-10 12:43 UTC
Labels: Bug, New Contributor Friendly
