### ISSUE TITLE
annotations missing at https://blog.jonudell.net/2016/04/02/owning-and-sharing-your-words/

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3236] opened 2016-04-20 15:15 UTC
### Repro

Visit https://blog.jonudell.net/2016/04/02/owning-and-sharing-your-words/

### Expected behaviour
These annotations:

AVPdOBrbH9ZO4OKSlh7j
AVPdWm4DH9ZO4OKSlh9Z
AVPhMs-TH9ZO4OKSljDi
AVPhNXY3H9ZO4OKSljD0
AVPhOaUfH9ZO4OKSljEk
AVPg-X33H9ZO4OKSli8a
AVPg89q2H9ZO4OKSli71
AVPg7kYVH9ZO4OKSli7i
AVPhBeBJH9ZO4OKSli9O
AVPhG7bEH9ZO4OKSli-x
AVPhIapZH9ZO4OKSli_s
AVPhMIf9H9ZO4OKSljDV
AVPhKo54H9ZO4OKSljC2
AVPhB8GtH9ZO4OKSli9Q
AVPhHOFuH9ZO4OKSli-1
AVPhMcUDH9ZO4OKSljDd
AVPhNq6KH9ZO4OKSljEC
AVPhoScOH9ZO4OKSljRE
AVPhk8_nH9ZO4OKSljPd
AVPg5ZNjH9ZO4OKSli7B
AVPhImEmH9ZO4OKSljAH
AVPhKUroH9ZO4OKSljCr
AVPg682nH9ZO4OKSli7b
AVPg9jPTH9ZO4OKSli7_
AVPg7HbRH9ZO4OKSli7d
AVPhC4PZH9ZO4OKSli9h
AVPg-kpXH9ZO4OKSli8g
AVPhJuUzH9ZO4OKSljCd
AVPhEuK-H9ZO4OKSli9y
AVPhLq9RH9ZO4OKSljDO
AVPhM9RHH9ZO4OKSljDn
AVPhNeQRH9ZO4OKSljD8
AVPhPMfgH9ZO4OKSljE3
AVPhOOntH9ZO4OKSljEc
AVPivBCZH9ZO4OKSljtH
AVPuRnLVH9ZO4OKSlm04
AVPnhEDBH9ZO4OKSlk4f
AVPg6Ap5H9ZO4OKSli7J
AVPg712-H9ZO4OKSli7m
AVPhGWgAH9ZO4OKSli-U
AVPxk6DgH9ZO4OKSlnZq
AVPuZa3RH9ZO4OKSlm3B
AVPxIOAbH9ZO4OKSlnPb
AVPucS1VH9ZO4OKSlm3r
AVP3ZiaMH9ZO4OKSlohn
AVP3ZiaDH9ZO4OKSlohm
AVPhnEKYH9ZO4OKSljQq
AVPhphMOH9ZO4OKSljRr
AVPuTqhZH9ZO4OKSlm1S
AVPvdK9vH9ZO4OKSlnBs
AVPvbm29H9ZO4OKSlnBP
AVPsyrg0H9ZO4OKSlmRZ

### Actual behaviour
Only this one: AVP3ZiaMH9ZO4OKSlohn

### Additional details
I got the list of annotations by scanning a recent database dump. Spot-checking, they seem to exist, but aren't being found by the query:

https://hypothes.is/api/search?uri=https%3A%2F%2Fblog.jonudell.net%2F2016%2F04%2F02%2Fowning-and-sharing-your-words%2F -> 1

**Comment by nickstenning** [comment] 2016-04-20 15:53
Looks like you've recently moved your blog to https?

https://hypothes.is/api/search?uri=http%3A%2F%2Fblog.jonudell.net%2F2016%2F04%2F02%2Fowning-and-sharing-your-words%2F
-> 39

As you know, you can attach the two URLs together by (temporarily) adding something like `<link rel="alternate" type="text/html" href="http://...">` and creating an annotation on the page. You can delete the annotation immediately afterwards.

**Comment by chdorner** [comment] 2016-04-20 15:55
@nickstenning this is actually a bit of a more wide-spread problem because WP.com recently [switched everybody to https](https://en.blog.wordpress.com/2016/04/08/https-everywhere-encryption-for-all-wordpress-com-sites/), and there's no link to the old http URLs.

**Comment by chdorner** [comment] 2016-04-21 16:33
I've added a new link to all the documents that link to a WP.com hosted blog, which fixed all documents where there is no canonical link. I have also made sure to add the same link to all annotations (`annotation[document[link]]`, so the postgres migration will preserve all these changes).

Now, the problem is that we don't expand the uri when it is the canonical one, which means that it doesn't work on the above-mentioned site. The only solution I can come up with is to change the `target[source]` of each annotation. But since that is quite a drastic method I want to check if there is anything else we can do?

**Comment by chdorner** [comment] 2016-04-21 20:01
Having had some time to think about it, how about changing the logic of [storage.expand_uri](https://github.com/hypothesis/h/blob/master/h/api/storage.py#L228-L231) to return a list of all `canonical` uris? That would fix the issue we're seeing with changing canonical uris, and it should probably also get rid of the issue with WP.com blogs, as long as they get a new annotation which adds the https canonical uri.
Any thoughts @nickstenning?

**Comment by chdorner** [comment] 2016-04-22 09:37
I just implemented the proposed fix I mentioned in the last comment, it is available for review at #3241

**Comment by chdorner** [comment] 2016-04-25 12:02
This is fixed on production now.

**Closed by chdorner** 2016-04-25 12:02 UTC

**Comment by nickstenning** [comment] 2016-06-13 11:29
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pN5ud6xV&#x2F;494-treat-http-https-urls-as-equivalent"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Treat HTTP&#x2F;HTTPS URLs as equivalent</a>
