### ISSUE TITLE
Deleted annotations no longer show replies

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2436] opened 2015-08-08 23:13 UTC
To recreate.

Create an annotation.
Create a reply to it.
Delete the first one.
Sign out and see if the reply is visible.  It's not.

**Comment by judell** [comment] 2015-08-12 23:47
Same as https://github.com/hypothesis/h/issues/2440?

**Comment by tilgovi** [comment] 2015-09-03 19:26
Please re-open with more detail.

**Comment by dwhly** [comment] 2015-09-03 19:31
Here's a video that shows it.  If the parent annotation is deleted, the replies no longer show.  
https://drive.google.com/file/d/0B0yW-dSdEYAcSmpxc2pFWVEzazA/view?usp=drivesdk

**Comment by judell** [comment] 2015-09-03 19:46
My expectation when deleting a parent might be a) of course children are deleted (but I might want to be warned), or b) a ghost of the parent remains as an anchor for the kids.

What do others expect?

**Comment by lenazun** [comment] 2015-09-03 19:49
Same. I would expect the children to be deleted with some warning.

**Comment by dwhly** [comment] 2015-09-03 19:56
There was a decision we made a while back to not allow people to delete entire threads of discussion by deleting their annotation, but to leave their annotation deleted as a stub, to which the replies would continue to persist.

**Comment by judell** [comment] 2015-09-03 20:06
So b) then. The ghost was designed/implemented? I don't recall seeing one, are there captures that show it?

**Comment by tilgovi** [comment] 2015-09-03 20:06
I would not implemented cascading delete because I'm still hoping to see Hypothesis support cross-repository annotation threads some days. The repository holding the annotation being deleted may not even be aware of the existence of the replies, let alone have authorization to delete them.

I think we started hiding top-level annotations rather than show a stub because the stub was ugly and we never invested time into figuring out what a good interface would be for such a situation.

**Comment by tilgovi** [comment] 2015-09-03 20:08
@judell make an annotation, reply, and reply again to that. Delete the middle one. The root will still appear and its reply will say "Message not available", but still have its reply in turn. The middle annotation is the ghost.

**Comment by seanh** [comment] 2015-11-23 10:53
> There was a decision we made a while back to not allow people to delete entire threads of discussion by deleting their annotation, but to leave their annotation deleted as a stub, to which the replies would continue to persist. That was implemented and functional, and this seems to be a regression afaict.

Do we want to bring this behaviour back, with the old _Message not available_ appearance? Or does this issue need some design work?

**Comment by dwhly** [comment] 2015-11-23 14:53
I think simply restoring the previous behavior is fine. Once we stare at it if we want to make a separate call as to design changes, we could create a new card for it.

**Comment by nickstenning** [comment] 2016-02-10 13:32
I'm not sure it's strictly accurate to call this a bug, but we'll roll with it for now.

**Comment by nickstenning** [comment] 2016-04-20 02:47
Regardless of the behaviour a long time ago, the entire system is currently designed in such a way that this is clearly not a bug/unintended behaviour. Closing.

**Closed by nickstenning** 2016-04-20 02:47 UTC
Labels: P3
