### ISSUE TITLE
Form fields shouldn't be modal

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4010] opened 2016-10-27 18:30 UTC
See [Slack discussion](https://hypothes-is.slack.com/archives/design/p1476281346000356).

![peek 2016-10-12 15-03](https://cloud.githubusercontent.com/assets/22498/19779877/d890289c-9c7a-11e6-92f7-53f44d15cc76.gif)

On the new forms when a form field has focus everything else on the page (other form fields, links...) is disabled and clicking them does nothing and doesn't give the user any indication as to why nothing is happening. The page is also greyed out, though this isn't very noticeable as our pages are mostly white and grey anyway.

The suggestion from Slack was:
1. If user hasn't entered or edited any text in the focused form field, then clicking on a link or another form field should just work, closing the focused field.
2. Optionally, if the user has made some changes in the focused field, show a popup (can be just an ugly browser popup) asking them if the want to lose their changes, and if they say yes then follow the link or change the focus to the field they clicked on.
   
   I say optionally because the other option for this one is to just follow links / focus fields and simply lose any unsaved changes without asking them. I've seen other sites including Slack and Grammarly do this.

**Comment by nickstenning** [comment] 2017-02-22 11:16
This is how the forms were designed, and thus how they were implemented. Closing as not a bug.

**Closed by nickstenning** 2017-02-22 11:16 UTC
Labels: Feature: Activity Pages
