### ISSUE TITLE
Chrome extension injects embed.js even when already present

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1946] opened 2015-02-12 20:49 UTC
Site's like JEP include an `embed.js` line:
http://quod.lib.umich.edu/j/jep/3336451.0017.201?view=text;rgn=main

If you have the Chrome extension on for that tab, you'll get a second h--which causes other issues.

**Comment by BigBlueHat** [comment] 2015-03-20 15:30
This is an increasing issue now that Via's in place and getting usage. If you have the Chrome extension on and visit a Via link...it'll likely kill your tab...at least it did for me just now.

**Comment by tilgovi** [comment] 2015-03-20 18:46
Closing as duplicate of #1688

**Closed by tilgovi** 2015-03-20 18:46 UTC
Labels: Bug, Chrome, Site Report
