### ISSUE TITLE
Annotation sharing links on owl.purdue.edu don't work

### ISSUE THREAD

**Issue by nhan000** [hypothesis/h#8110] opened 2023-08-10 21:35 UTC
Sorry if this is not the right place to file bug reports. If so please redirect me elsewhere.

How to reproduce the bug:
1. Go to https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/reference_list_electronic_sources.html
2. Make a highlight.
3. Click the "Share" button, copy, and open the link in a new tab.
![image](https://github.com/hypothesis/h/assets/85216095/c7eb530d-65fc-40c8-99c6-7153ebb8f715)
4. See that the link is broken because `https://owl.purdue.edu/` becomes `https://www.owl.purdue.edu/`. The webpage can't be opened.
![image](https://github.com/hypothesis/h/assets/85216095/cfcfb2e2-d547-4705-ac43-d3f4afba1824)

**Comment by robertknight** [comment] 2023-08-11 07:02
This page has a `<link rel=canonical>` tag in the page with the broken URL:

```html
<link href="https://www.owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/reference_list_electronic_sources.html" rel="canonical">
```

Where a page declares a canonical link, it overrides the actual URL of the page in Hypothesis.

The sharing link for an annotation contains an ID and the URL of the page. The page URL is not actually used, it is just there for readability. The URL that is stored with the annotation is what matters, and here that URL comes from the page's `<link rel=canonical>` tag.

**Comment by robertknight** [comment] 2023-09-01 12:28
Closing the issue as the problem is with the website itself.

**Closed by robertknight** 2023-09-01 12:28 UTC
