### ISSUE TITLE
annotations missing at http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate/

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3160] opened 2016-03-31 00:27 UTC
### Steps to reproduce
1. http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate/

### Expected behaviour
Only one public annotation appears.

### Actual behaviour
16 should, based on https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.cnn.com%2F2015%2F05%2F05%2Fopinions%2Fsutter-sea-level-climate%2F

**Comment by nickstenning** [comment] 2016-04-20 00:35
The issue here is that the page declares the following `<link rel="canonical">`:

```html
<link rel="canonical" href="http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate/index.html">
```

As discussed at length in #2652, this means that we'll query for only those annotations which were made on a page with either a) exactly this URL, or b) the same  `<link rel="canonical">` tag. The problem you've identified here is [explicitly called out in that issue](https://github.com/hypothesis/h/pull/2652#issuecomment-150204038) as being a result of the change.

Given that we know about this behaviour, and reverting it simply creates different problems, I'm going to close this as not a bug.

**Closed by nickstenning** 2016-04-20 00:35 UTC
Labels: P3
