### ISSUE TITLE
Inactive Firefox extension kills embedded h

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1901] opened 2015-01-31 11:07 UTC
Having the extension turned off, when visiting a page with h embedded, the (collapsed) sidebar appears momentarily and then disappears. It works fine in private browsing mode (so no extension), so my guess is that the extension is the culprit.

**Comment by BigBlueHat** [comment] 2015-02-03 18:36
Duplicate of #1689.

**Closed by BigBlueHat** 2015-02-03 18:36 UTC
Labels: Bug
