### ISSUE TITLE
unable to delete annotation (resolved itself, but may indicate es/pg sync issue?)

### ISSUE THREAD

**Issue by judell** [hypothesis/h#5200] opened 2018-07-30 20:40 UTC
The annotation in question: https://hyp.is/KJ3-fpOyEeiEU3dP16qjvA/www.npr.org/2018/07/29/632994245/zimbabwes-rickety-trains-get-a-boost-from-expat-investors-next-door

The view from the client: 

![image](https://user-images.githubusercontent.com/46509/43422211-dd13157e-93fd-11e8-9978-c630458182f6.png)

The API search the client is making:

https://hypothes.is/api/search?_separate_replies=true&group=__world__&limit=200&offset=0&order=asc&sort=created&uri=https%3A%2F%2Fwww.npr.org%2F2018%2F07%2F29%2F632994245%2Fzimbabwes-rickety-trains-get-a-boost-from-expat-investors-next-door

Update: And now it's gone. So, a temporary disagreement between elasticsearch and postgres?

Also, however, the badge API call, https://hypothes.is/api/badge?uri=https%3A%2F%2Fwww.npr.org%2F2018%2F07%2F29%2F632994245%2Fzimbabwes-rickety-trains-get-a-boost-from-expat-investors-next-door , is returning:

```
{"total": 1}
```

**Comment by robertknight** [comment] 2018-09-14 23:26
See also: 
https://github.com/hypothesis/h/issues/5227#issuecomment-419951912

**Comment by robertknight** [comment] 2018-11-22 14:52
I'm going to consider this a duplicate of https://github.com/hypothesis/h/issues/5227.

**Closed by robertknight** 2018-11-22 14:52 UTC
Labels: bug
