### ISSUE TITLE
Modifications to target_selector will not be saved

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3271] opened 2016-05-03 13:45 UTC
If you mutate (rather than replace) a Postgres annotation ORM object's extra, target_selector or tags the changes will not be saved when the transaction is committed. See https://github.com/hypothesis/h/pull/3256#discussion_r61466432. Fix and then remove the workaround the comment is in response to.

**Comment by nickstenning** [comment] 2016-06-23 13:04
This is now fixed for `tags` and `extra` as of #3417.

**Comment by nickstenning** [comment] 2017-02-21 14:56
I'm going to go ahead and close this. It's not a bug -- the system is working as designed, even if it isn't ideal.

**Closed by nickstenning** 2017-02-21 14:56 UTC
