### ISSUE TITLE
Annotations on PDFs (in FF 33 at least) seem out of order

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1647] opened 2014-11-07 03:21 UTC
Testing on this document:
http://faculty.georgetown.edu/irvinem/theory/Berners-Lee-HTTP-proposal.pdf

I have 2 public annotations there, and 1 private one. Sort is set to `location`. As I scroll the order of the cards swap...and I can't (yet) discern the pattern.

**Comment by tilgovi** [comment] 2015-05-11 22:12
Still a problem. Guessing that this is a matter of the order of the cards in the sidebar being determined by the information we pass to it about the absolute positions of the highlights in the document, but for PDF.js this changes as page divs are made visible and hidden as one scrolls. The swap occurs when something else causes a cross-frame sync and new position information is propagated to the sidebar.

**Comment by judell** [comment] 2015-06-11 21:54
I am not seeing this in Chrome or FF at the moment.

**Comment by tilgovi** [comment] 2015-06-11 21:57
I'll close it optimistically. We'll open it up if we see it after the new anchoring work merges, but at this point I've got tests on that branch that ensure that annotations will have accurate position information as they re-anchor and pages re-render. I don't know if that was the case before or not.

**Comment by judell** [comment] 2015-06-19 19:07
Reopening because I'm seeing multiple out-of-order issues, for PDFs and HTMLs, in FF and Chrome.   I'm gathering evidence now. At this point we may want to focus on resolving them in the context of the test extension that includes the new anchoring mechanism. I guess we can still use this issue to capture the evidence I'm finding.

**Comment by tilgovi** [comment] 2015-07-21 20:54
It is expected that annotations are at least in order by page now, but due to the lazy rendering of pages with PDF.js they may be out of order within a page.

**Comment by tilgovi** [comment] 2015-08-13 04:20
I can't reproduce this anymore.

**Closed by tilgovi** 2015-08-13 04:20 UTC
Labels: Bug, P3
