### ISSUE TITLE
"You do not have permission to view this annotation." for own highlight

### ISSUE THREAD

**Issue by akuckartz** [hypothesis/h#3411] opened 2016-06-04 10:11 UTC
### Steps to reproduce
1. Login to hypothes.is
2. Highlight a number of text fragments in a PDF file using via.hypothes.is
3. View the list of annotations
### Expected behaviour

All highlight-annotations should be visible in the list
### Actual behaviour

The first annotations are displayed. For the rest "You do not have permission to view this annotation." is shown.
### Browser/system information

Chrome 50.0.2661.102 on Windows 10.
### Additional details

hypothes.is account akuckartz

**Comment by dwhly** [comment] 2016-06-04 10:31
@akuckartz:

I'm trying to repro this with the steps you've listed, and cannot.  I open a PDF file, make a number of highlights, and I can see them all without issue both on the document, and in my personal stream.

Can you perhaps screencapture this issue?  I don't doubt that it's happening, just that I can't seem to reproduce.  Also, you might provide all the detail available under "About this version" in the user dropdown menu if you are comfortable doing so.

**Comment by akuckartz** [comment] 2016-06-04 11:35
Meanwhile I updated Chrome and also installed and tried the Plugin for Chrome - no improvement.

The correct content of the annotation cards (correct term?) become visible when I click on "Show all ... annotations".

~~~
About this version
Version:
0.25.0
User agent:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
URL:
https://www.bmvi.de/SharedDocs/DE/Anlage/Digitales/faq-foerdernehmer-mfund.pdf?__blob=publicationFile
PDF fingerprint:
6ad8fb1d405b8b4e8d474abf77f1fc4e
Username:
akuckartz
Date:
04 Jun 2016 13:31:48 +0200
~~~

Thanks for the quick reaction. I will try to provide a screenshot.

**Comment by akuckartz** [comment] 2016-06-04 13:17
Does this screenshot help to diagnose the issue?

![hypthesis issue](https://cloud.githubusercontent.com/assets/327651/15799761/39d5372c-2a67-11e6-8283-96cf7f4cdc5e.png)

**Comment by dwhly-proj** [comment] 2016-06-04 17:35
A screencast is more helpful if possible.

**Comment by nickstenning** [comment] 2017-02-21 14:24
Hi Andreas. I'm afraid I'm unable to reproduce this bug with the instructions provided here. I'm going to close this issue. If you run into this problem again please do reopen with instructions that will help us reproduce the issue.

**Closed by nickstenning** 2017-02-21 14:24 UTC
