### ISSUE TITLE
Chrome extension does not handle PDFs served without a .pdf extension

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2058] opened 2015-03-18 19:05 UTC
Open in chrome. Deploy extension. Adder never shows after selection.
http://www.tandfonline.com/doi/pdf/10.1080/03626784.2014.995063

**Comment by tilgovi** [comment] 2015-03-18 19:25
This is not expected to work as is because this site is not serving the PDF, it's embedding and using PDF.js itself.

We need to change this issue title to reflect the root problem and discuss potential solutions. We used to have some solutions, but they seemed brittle to me and I made us strip them out before we shipped the Chrome extension with PDF support finalized.

**Comment by tilgovi** [comment] 2015-03-18 19:36
Oh, my mistake. They _are_ serving the PDF directly, just without a .pdf extension.

For FF, it doesn't matter, because we don't need to do anything special. We use the built-in PDF.js anyway.

For Chrome, we need to detect the presence of the PDF loaded in Chrome's viewer and switch to our bundled PDF.js.

I thought this was going to be about detecting the PDF.js element inside a publisher's page. That's not the case, so I'm removing that from the table for now, still. That's what I was referring to with the previous "solutions" (to what I now see is a different problem).

I _think_ I'm okay with detecting body > embed[type=application/pdf].

**Comment by tilgovi** [comment] 2015-03-18 19:36
Updated title.

**Comment by csillag** [comment] 2015-03-18 21:08
Closing as a duplicate of #1900.

**Closed by csillag** 2015-03-18 21:08 UTC
Labels: Site Report

**Comment by tilgovi** [comment] 2015-03-18 21:16
Thanks, @csillag.
