### ISSUE TITLE
Fonts broken on GitHub

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2266] opened 2015-06-02 15:58 UTC
Refused to load the font 'data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMg8SA1…B5ACAASQBjAG8ATQBvAG8AbgAuAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==' because it violates the following Content Security Policy directive: "font-src assets-cdn.github.com".

**Comment by seanh** [comment] 2015-06-02 15:58
Current production and master

**Comment by tilgovi** [comment] 2015-06-03 17:43
Once upon a time we had #200 open. The only way around this that I can see is to have every single bit of our UI that might need to use the icon font in an iframe or to not use an icon font for these things.

**Comment by judell** [comment] 2015-06-12 19:48
We're talking about this, right?

![image](https://cloud.githubusercontent.com/assets/46509/8138599/20f13ce0-1101-11e5-838f-54771624bee2.png)

It's super-annoying.

What's the downside to punting on the icon font?

**Comment by seanh** [comment] 2015-06-12 21:18
Yes that's the one

**Comment by pguth** [comment] 2015-08-11 23:05
I had that too. Now `h` is broken completely on Github.

```sh
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".
```
`hypothesis.min.js?cd8bafb3:6`

**Comment by tilgovi** [comment] 2015-08-11 23:27
I suspect Github may have changed their CSP rules.

**Comment by tilgovi** [comment] 2015-08-11 23:28
Oh, I'm wrong! I'm looking into it.

**Comment by tilgovi** [comment] 2015-08-11 23:33
Tracked it down. Filed this. Not sure whether it'll be well received or not. https://github.com/tarruda/has/issues/5

**Comment by tilgovi** [comment] 2015-08-11 23:34
This comes in as a result of us switching to frame-rpc instead of jschannel.

**Comment by tilgovi** [comment] 2015-08-11 23:34
@judell alright, you can make this a separate issue now.

**Comment by irtzaqc** [comment] 2016-01-25 04:43
Is this issue still open? Cause I am facing this problem myself right now....any ETA on potential fixes?

**Comment by robertknight** [comment] 2016-01-25 08:21
@irtzaqc Yes it is. I'm currently in the middle of some refactoring of the way we build the Chrome extension and should be able to fix this problem in the process. So it should get fixed within the next couple of weeks.

**Comment by irtzaqc** [comment] 2016-01-26 17:41
@robertknight just to make sure, the fix will be to the github csp yeah? it'll allow us to use self as a font-src?

**Comment by robertknight** [comment] 2016-01-26 18:08
@irtzaqc I'm afraid I don't understand your question. The issue is that the icons in the sidebar do not load properly when the sidebar is opened on github.com pages. That is what I intend to fix.

The reason fonts are broken is because the sidebar's CSS references an icon font using a data URL which is disallowed by GitHub's CSP. The fix will be to have the CSS reference the icon font via a `chrome-extension://` URL instead.

**Comment by irtzaqc** [comment] 2016-01-26 18:09
Ah okay. Apologies. I misunderstood the issue :)

**Comment by robertknight** [comment] 2016-02-22 07:42
https://hypothesis.zendesk.com/inbox/tickets/160

**Comment by tilgovi** [comment] 2016-02-22 15:24
That doesn't not seem to be a public link.

**Comment by robertknight** [comment] 2016-02-22 16:57
@tilgovi - It isn't I'm afraid. I can't reproduce the support message here but it refers to this URL: http://www.cnn.com/2014/04/17/health/adderall-college-students/

**Comment by tilgovi** [comment] 2016-02-22 17:11
I can't recall my original reasons for keeping the toolbar controls outside the sidebar iframe. The most surefire way to solve all these issues might be to put them back inside.

**Closed** 2016-02-23 12:46 UTC
Labels: Browser: Chrome, P3, Web Page Compatibility
