### ISSUE TITLE
Highlights created whilst signed out cannot be deleted

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3348] opened 2016-05-23 07:50 UTC
### Steps to reproduce
1. Go to a page and activate Hypothesis.
2. Sign out
3. Create a highlight and select it
### Expected behaviour
1. After signing in, the highlight can be deleted whilst focused
2. When the highlight is focused, a 'You do not have permission...' message should not be shown in the sidebar. TBD: What _should_ be shown?
### Actual behaviour
1. When the highlight is focused in the page, the sidebar displays a 'You do not have permission to see this annotation' message
2. After signing in, the highlight shows the signed-in account name on the annotation card but the highlight cannot be deleted
### Browser/system information

Tested in current build of MS Edge

**Comment by nickstenning** [comment] 2017-02-21 13:10
There are all kinds of bugs with highlighting while logged out, but I can't reproduce this one. Closing.

**Closed by nickstenning** 2017-02-21 13:10 UTC
