### ISSUE TITLE
No annotation URL via date stamp or share icon available on local PDFs

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3440] opened 2016-06-09 17:08 UTC
### Steps to reproduce
1. Drag a local PDF to the browser
2. Turn on the extension
3. Make an annotation
4. Click either the date stamp or the share icon
### Expected behaviour

The date stamp should take you to the standalone annotation page.
The share icon should probably reveal the same standaone annotation URL (since direct links to local files don't make sense).
### Actual behaviour

Clicking the date stamp takes you too an odd chrome-extension URL:  (e.g. unsafe:chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/null)
Clicking the share icon on an annotation shows a blank URL box.
### Browser/system information

Chrome extension 0.27

**Comment by nickstenning** [comment] 2017-02-21 14:40
I can't reproduce this in 0.56. Closing.

**Closed by nickstenning** 2017-02-21 14:40 UTC
