### ISSUE TITLE
Check over PyLint's Python 3 messages

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5517] opened 2019-01-30 13:35 UTC
<del>Get stronger linting in place, and</del> review the linter warnings for Python 3 problems.

Pylint can check for lots of Python 3 problems and can enforce that they stay fixed. Our codebase is currently in bad shape with PyLint: we have a lot of warnings. <del>Get `make lint` running the stronger Prospector linter (which runs PyLint) and run it on CI.</del> We won't try to fix all the linter warnings before moving to Python 3 (there'd be too many), but I'd like to:

- <del>[ ] Get a ratchet mechanism in place: Something (perhaps a unit test) that runs prospector and:</del>

  * <del>Looks at the set of files that contain warnings and doesn't allow any new files that didn't have any linter warnings before to grow any</del>
  * <del>Counts the total number of linter warnings across all files (or maybe per-file?) and doesn't allow it to increase</del>

- [ ] Do a review of the existing <del>Prospector</del>PyLint warnings for any Python 3 problems. (Globally disabling unimportant warnings that are triggered many times will allow the output to be reviewed more easily.)

**Comment by seanh** [comment] 2019-03-01 18:26
For the purposes of the Python 3 migration I've edited the description above to be just about checking PyLint's Python 3 warnings, and not about getting a PyLint ratchet installed on CI.

Maybe we can fix or disable all the Python 3 PyLint warnings (and only those ones) and then run PyLint on CI with only the Python 3 warnings enabled to ensure that no new Python 3 warnings can be added.

**Comment by seanh** [comment] 2019-03-01 18:35
[Prospector](https://prospector.readthedocs.io/) is a meta-linter that runs several actual linters:

* PyLint (deep code analysis)
* pycodestyle (we already run this on CI via flake8, so we don't have any pycodestyle warnings)
* pydocstyle (docstrings, not relevant to the Python 3 move)
* pyflakes (we already run this on CI via flake8, so we don't have any pyflakes warnings)
* mccabe (I think we already run this on CI via flake8, so I don't think we have any mccabe warnings, also not relevant to the Python 3 move)
* dodgy (checks for things that look like secrets or passwords etc in your code, not relevant to the Python 3 move)
* pyroma (checks your setup.py, h doesn't have one)
* vulture (checks for unused code, not relevant to the Python 3 move)
* frosted (stagnated pyflakes fork, not interesting)
* mypy (static type checking, not interesting)

So the only thing that Prospector runs that we're interested in here is PyLint.

**Comment by seanh** [comment] 2019-03-01 18:41
PyLint conveniently groups all of its Python 3-related messages under its python3 checker: http://pylint.pycqa.org/en/latest/technical_reference/features.html?highlight=similarities#python3-checker

Using the PyLint stuff from <https://github.com/hypothesis/h/pull/5556> I ran PyLint with the python3 rules only:

```shellsession
$ .tox/py36-analyze/bin/pylint  -j 0 --score=no --disable=all --enable=python3 --disable=no-absolute-import h tests
```

Here are the results:

```
************* Module h._compat
h/_compat.py:28:16: W1612: unicode built-in referenced (unicode-builtin)
h/_compat.py:29:25: W1612: unicode built-in referenced (unicode-builtin)
h/_compat.py:30:13: W1613: xrange built-in referenced (xrange-builtin)
h/_compat.py:31:13: W1635: unichr built-in referenced (unichr-builtin)
h/_compat.py:49:16: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:50:21: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:51:18: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:52:23: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:78:25: W1612: unicode built-in referenced (unicode-builtin)
************* Module h.cli.commands.user
h/cli/commands/user.py:40:61: W1661: Using an exception object that was bound by an except handler (exception-escape)
h/cli/commands/user.py:40:61: W1645: Exception.message removed in Python 3 (exception-message-attribute)
************* Module h.models.user
h/models/user.py:50:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module h.activity.bucketing
h/activity/bucketing.py:20:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module h.schemas.forms.admin.group
h/schemas/forms/admin/group.py:65:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.schemas.forms.accounts.forgot_password
h/schemas/forms/accounts/forgot_password.py:31:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.schemas.forms.accounts.login
h/schemas/forms/accounts/login.py:38:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/schemas/forms/accounts/login.py:45:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/schemas/forms/accounts/login.py:50:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.accounts.schemas
h/accounts/schemas.py:180:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/accounts/schemas.py:206:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/accounts/schemas.py:209:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module tests.h.util.document_claims_test
tests/h/util/document_claims_test.py:239:42: W1654: dict.items referenced when not iterating (dict-items-not-iterating)
************* Module tests.h.util.query_test
tests/h/util/query_test.py:28:22: W1649: Accessing a deprecated function on the string module (deprecated-string-function)
************* Module tests.h.views.accounts_test
tests/h/views/accounts_test.py:737:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module tests.h.views.admin.groups_test
tests/h/views/admin/groups_test.py:293:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module tests.h.views.admin.organizations_test
tests/h/views/admin/organizations_test.py:150:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
tests/h/views/admin/organizations_test.py:178:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module tests.h.views.admin.oauthclients_test
tests/h/views/admin/oauthclients_test.py:158:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
tests/h/views/admin/oauthclients_test.py:190:15: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module tests.h.search.index_test
tests/h/search/index_test.py:548:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module tests.h.services.group_members_test
tests/h/services/group_members_test.py:242:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module tests.h.services.group_create_test
tests/h/services/group_create_test.py:497:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module tests.h.services.group_test
tests/h/services/group_test.py:213:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/h/services/group_test.py:226:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module tests.common.matchers
tests/common/matchers.py:36:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:44:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:52:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:85:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:98:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:111:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:129:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:141:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:153:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
tests/common/matchers.py:166:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
```

**Comment by robertknight** [comment] 2019-10-08 06:32
I re-ran this on the current code in the `h/` dir. I ignored the tests because if they are passing under Python 3, there isn't really anything more to do there.

```
> .tox/py36-analyze/bin/pylint  -j 0 -f text --score=no --disable=all --enable=python3 --disable=no-absolute-import h/

************* Module h.paginator
h/paginator.py:11:29: W1619: division w/o __future__ statement (old-division)
************* Module h._compat
h/_compat.py:22:16: W1612: unicode built-in referenced (unicode-builtin)
h/_compat.py:23:25: W1612: unicode built-in referenced (unicode-builtin)
h/_compat.py:24:13: W1635: unichr built-in referenced (unichr-builtin)
h/_compat.py:37:16: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:38:21: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:39:18: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
h/_compat.py:40:23: W1658: Accessing a removed attribute on the urllib module (deprecated-urllib-function)
************* Module h.activity.bucketing
h/activity/bucketing.py:18:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module h.models.user
h/models/user.py:49:0: W1641: Implementing __eq__ without also implementing __hash__ (eq-without-hash)
************* Module h.cli.commands.user
h/cli/commands/user.py:40:61: W1661: Using an exception object that was bound by an except handler (exception-escape)
h/cli/commands/user.py:40:61: W1645: Exception.message removed in Python 3 (exception-message-attribute)
************* Module h.schemas.forms.admin.group
h/schemas/forms/admin/group.py:64:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.schemas.forms.accounts.login
h/schemas/forms/accounts/login.py:36:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/schemas/forms/accounts/login.py:43:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/schemas/forms/accounts/login.py:48:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.schemas.forms.accounts.forgot_password
h/schemas/forms/accounts/forgot_password.py:29:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
************* Module h.search.index
h/search/index.py:233:19: W1619: division w/o __future__ statement (old-division)
************* Module h.accounts.schemas
h/accounts/schemas.py:179:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/accounts/schemas.py:205:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
h/accounts/schemas.py:208:12: W1624: Indexing exceptions will not work on Python 3 (indexing-exception)
```

Of the above:

- Issues in `h._compat` will go away when the file is removed
- Warnings about division are obsolete in Python 3
- The "indexing exceptions" warnings are false positives because of setting exception messages for fields on `colander.Invalid` exceptions using `exc["field_name"] = ...`
- The `__eq__ without __hash__` warnings are irrelevant if the objects are never stored in a dict/set. This seems like it would mostly be a consideration if implementing library code where it isn't known how consumers might want to use it
- The warning about `Exception.message` does actually indicate a bug. I was able to reproduce by using `./bin/hypothesis user add` and trying to add a user with a username that already exists. The "Using an exception object that was bound by an except handler" warning on the same line looks like a false positive to me as the error is not in fact used outside of the except handler. The code works once I fixed the previous issue.

**Comment by robertknight** [comment] 2019-10-08 12:51
From https://github.com/hypothesis/h/issues/5384:

>  Review PyLint warnings for Python 3 problems, fix them, and run PyLint on Travis (with only the Python 3 warnings enabled) so that they stay fixed

I think the discussion here and https://github.com/hypothesis/h/pull/5739 covers the first part of that. The part that is not done is running PyLint regularly. Given that we've already moved to Python 3 though, running it with Python 3 warnings at this point would I think be a bit pointless.

We might want to run additional static analysis tools to catch other issues as part of CI, but at this point it is no longer about the Python 3 migration. On that basis, are you ok with marking this issue as resolved @seanh?

**Comment by robertknight** [comment] 2020-10-15 09:09
h has been running Python 3.6 in production for over a year so I'm going to close this. The evolution of static analysis in Python code is an ongoing task.

**Closed by robertknight** 2020-10-15 09:09 UTC
Labels: Python 3
