### ISSUE TITLE
Public annotation showing when scope is set to a group

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2734] opened 2015-11-21 19:01 UTC
To repro:
- Join this group: https://hypothes.is/groups/wXrz5Y93/bio
- Make sure you're navigated to it in on a page, so that the scope control is set to "Bio!"
- Go to this PDF http://www.tarletongillespie.org/essays/Gillespie%20-%20The%20Relevance%20of%20Algorithms.pdf
- Turn on the prod chrome extension.
- The Public annotation there should be showing even though "Bio!" is active.

Screenshot:
![screenshot 2015-11-21 10 58 31](https://cloud.githubusercontent.com/assets/1413074/11319964/2b3bdb84-903f-11e5-898e-b587578e20aa.png)

**Comment by robertknight** [comment] 2015-11-21 19:45
Looks like a dupe of #2715

**Comment by nickstenning** [comment] 2015-11-23 15:40
Closing as a duplicate.

**Closed by nickstenning** 2015-11-23 15:40 UTC
Labels: Bug, P2
