### ISSUE TITLE
Safari doesn't load annotations

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2076] opened 2015-03-23 23:12 UTC
Surfacing this from a forum post:

> It seems that via.hypothes.is does not work with Safari.
> For instance, visiting this link https://via.hypothes.is/h/http://mashable.com/2015/03/16/vanuatu-cyclone-pam-global-warming/
> with Firefox or Chrome shows annotations, but no annotation show with Safari.

This is seen in (at least) version 6.1.6.

**Comment by dwhly** [comment] 2015-03-23 23:23
Verified earlier w/ Safari 8 using Sauce.

**Comment by tilgovi** [comment] 2015-03-23 23:33
I can verify through Sauce but debugging that was is a PITA. Leaving this for someone with a mac.

**Comment by RawKStar77** [comment] 2015-03-24 19:08
In Safari 8 I'm getting a lot of errors from the mashable page and nothing that obviously looks like h, but this looks a little suspicious:
```
Refused to display 'https://apis.google.com/u/0/_/widget/render/follow?usegapi=1&annotation=bubble&height=20&rel=author&origin=https%3A%2F%2Fvia.hypothes.is&url=https%3A%2F%2Fvia.hypothes.is%2Fh%2Foe_%2Fhttp%3A%2F%2Fplus.google.com%2F%2BMashable&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.X8rceIahMj4.O%2Fm%3D__features__%2Fam%3DIQ%2Frt%3Dj%2Fd%3D1%2Ft%3Dzcms%2Frs%3DAGLTcCPJ88QQoiwv46VFmvMDcYegbwyu5Q#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&id=I0_1427198634455&parent=https%3A%2F%2Fvia.hypothes.is&pfname=&rpctoken=15389782' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

**Comment by BigBlueHat** [comment] 2015-03-24 19:20
Yeah... Let's also test this on something less dynamic or picky.

I often use http://w3.org/DesignIssues and things linked from there.

**Comment by rdhyee** [comment] 2015-03-27 18:57
My annotation is not loading on Safari either (Version 7.1.4 (9537.85.13.7), running on OS X 10.9.5).  Specifically, I was expecting 

https://hypothes.is/a/Y177M3SnQXaCbTnpKyLeIg

to show on https://via.hypothes.is/h/http://berkeley-dhwg.org/dh-faire/  but it doesn't in my Safari browser.

**Comment by seanh** [comment] 2015-03-31 12:23
I'm gonna punt on this one as well, it's just a really ineffective use of my time to be trying to investigate this from Linux.

I can reproduce the issue in both saucelabs and browserstack using the latest OS X/Safari. As @BigBlueHat says it's easier to use this page http://w3.org/DesignIssues to reproduce, much less noisy. 

But as far as I can tell you can't view the details of HTTP requests in the Safari dev tools! So I can't get far with debugging it.

Browserstack claims to have Firebug Lite installed but the button does nothing. Can't install the h bookmarklet in Safari in saucelabs or browserstack either.

Needs someone with a mac who can debug Safari issues more effectively!

**Comment by RawKStar77** [comment] 2015-04-02 23:35
On my mac now and looking into this. It's quite strange as there are no console errors on the example @rdhyee pointed out: https://via.hypothes.is/h/http://berkeley-dhwg.org/dh-faire/

Meanwhile this page seems to work: https://via.hypothes.is/h/http://arstechnica.com/gaming/2015/04/valve-software-co-founder-gabe-newell-becomes-a-video-game-character/

**Comment by judell** [comment] 2015-04-10 00:03
Referencing https://github.com/hypothesis/h/issues/2129

**Comment by tilgovi** [comment] 2015-04-17 00:50
I think this is the same as my diagnosis in https://github.com/hypothesis/h/issues/2129#issuecomment-93869450 and can therefore be closed.

**Comment by tilgovi** [comment] 2015-04-17 02:09
Seeing no problems in Safari 8 now. But reports coming in that Safari 7 still having trouble.

**Comment by tilgovi** [comment] 2015-04-18 02:11
Using the original link in the issue description I now see the same annotations on OSX Mavericks and Safari 7 (using via on BrowserStack) as I do locally with Firefox (bookmarklet) and Chrome (extension).

The link that @rdhyee shared has no annotations anchoring in any browser I test, though they do show up in the search results return when I look in the network tab of my dev tools. There's an anchoring issue there, for sure, but it's not Safari specific.

I'll close this bug. \o/

**Closed by tilgovi** 2015-04-18 02:11 UTC
Labels: 1 - Backlog, Bug, Site Report, Sprint Priority, Support Request

**Comment by dwhly** [comment] 2015-04-18 02:33
Nice!

**Comment by RawKStar77** [comment] 2015-04-18 02:51
:fireworks:
