### ISSUE TITLE
DomTextMapper freezes/slugs browser while scanning page

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1893] opened 2015-01-28 13:12 UTC
Loading the extension on a page can take so much cpu time that it freezes the browser for some seconds.

On some pages (e.g. docs.meteor.com), it can take so long that browsers think it's completely unresponsive:
![screenshot1](https://cloud.githubusercontent.com/assets/4191409/5937986/0282a6b6-a6ff-11e4-9e11-44f096930131.png)

Related to #1224.

**Comment by tilgovi** [comment] 2015-02-02 16:00
This is a known issue. Duplicate of hypothesis/dom-text-mapper#45

**Closed by tilgovi** 2015-02-02 16:00 UTC
Labels: 1 - Backlog, Bug
