### ISSUE TITLE
Chrome extension doesn't work on Github

### ISSUE THREAD

**Issue by vishaltelangre** [hypothesis/h#2845] opened 2016-01-11 05:15 UTC
![image](https://cloud.githubusercontent.com/assets/876195/12227310/6093346a-b850-11e5-82ce-ea41b4d25f02.png)

**Comment by robertknight** [comment] 2016-01-11 10:19
This is related to / duplicate of #2445 , #2769 , #2427 , #2266

**Comment by seanh** [comment] 2016-01-11 12:13
[This commit](https://github.com/hypothesis/h/commit/f5b16aa1a9ef68abf9a4f1a89f19e569fece4f8f) introduced the [frame-rpc](https://www.npmjs.com/package/frame-rpc) module into `bridge.coffee` for inter-frame communication.

frame-rpc in turn [requires](https://github.com/substack/frame-rpc/blob/master/index.js#L1) the [has](https://www.npmjs.com/package/has) module, and has [requires](https://github.com/tarruda/has/blob/master/src/index.js#L1) [function-bind](https://www.npmjs.com/package/function-bind), and function-bind [does the equivalent of an eval()](https://github.com/Raynos/function-bind/blob/master/index.js#L38).

This causes the Content-Security-Policy error `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com"` from GitHub

**Closed** 2016-01-11 18:33 UTC
Labels: Web Page Compatibility
