### ISSUE TITLE
Highlight CSS (?) problem over PDF.js

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2022] opened 2015-03-11 08:12 UTC
As reported by a user:

> In pdfs when you scroll over the annotation, it turns blue, but its solid. In other words you can't see the text. The blue box covers up the text.

**Comment by csillag** [comment] 2015-03-11 17:31
@raziellight, can you give us some details on this one, too?
I would love to hunt this down, but I can't seem to be able to reproduce this locally.

So, I would like to know borwser version, platform, PDF.js version and document URL, if possible. Thank you.

**Comment by tilgovi** [comment] 2015-03-13 21:15
The highlights used to blend but it presented a different set of problems on PDF due to the way the text layers work. I can't recall the exact issue, but I can dig if you need me to. I think this is a "won't fix" right now.

**Comment by dwhly** [comment] 2015-03-16 01:18
I notice that this seems to be limited to via.  For instance, here:
https://via.hypothes.is/static/ann/viewer/web/viewer.html?file=/h/id_/http://langsci-press.org/catalog/view/48/11/207-1

Doesn't matter if it's chrome or FF.

But take the PDF:
http://langsci-press.org/catalog/view/48/11/207-1

Download it (since it doesn't want to open in the browser) and drag it to Chrome tab.  Turn on the extension-- the highlights work as they should.

**Comment by tilgovi** [comment] 2015-05-11 21:52
I cannot reproduce this. We know that PDF.js changed the transparency of their text layer and this effected our highlights but we detect this for a while now and modify the transparency of our highlights accordingly. I don't expect this is a problem anymore and since we don't know what environment the user reporting this was in, I don't think we can follow up.

**Closed by tilgovi** 2015-05-11 21:52 UTC
Labels: Bug

**Comment by raziellight** [comment] 2015-05-20 05:24
I'm the user who reported it. It was on PDF.js v1.0.907 (build: e9072ac), windows 7, chrome version Version 42.0.2311.152 m, but it appears to be fixed now. I am not getting the same issue anymore. It appears to be fixed.
