### ISSUE TITLE
New annotations don't appear to have keyboard focus (until you start typing)

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2126] opened 2015-04-02 19:41 UTC
When the user creates a new annotation the sidebar automatically scrolls to show it, but the keyboard focus is not always automatically in the new annotation's text area. Sometimes it is, sometimes it isn't.

**Comment by RawKStar77** [comment] 2015-04-07 23:47
I can't reproduce this. Any steps to preform or a site where this happens?

**Comment by seanh** [comment] 2015-04-08 17:29
Hmm, I really have seen this lots of times, but now I can't figure out how to reproduce it on master. Closing for now

**Comment by edrex** [comment] 2015-09-21 17:28
Input focus isn't set to the new annotation text field for me (ever). 

Chrome 45.0.2454.93 OS X, using the chrome browser app. 

This costs a scan/seek/click cycle, which the user really feels IMO, after waiting for the initial overlay load and clicking the "New Note" button. 

Auto-scrolling to the new annotation works.

Should I report this as a new issue or would reopening this make sense?

**Comment by dwhly** [comment] 2015-09-21 18:12
While the bootstrappy blue border isn't active on the text edit box, if you start typing you should see that the actual focus is on the element.  We should fix the first, but just checking that you're seeing that the focus is indeed set correctly.

**Comment by edrex** [comment] 2015-09-22 04:30
Ah, when I start typing the focus is switched to the new annotation input box. But it's only switched once I start typing, so the visual focus indication is broken. Is there any reason not to switch the focus when the note is initiated instead of after the first keystroke?

**Comment by seanh** [comment] 2015-09-22 10:16
Yep, I can reproduce it as @dwhly and @edrex say on master: text area does not appear to be focused but if you start typing it is. Re-opening

**Comment by tilgovi** [comment] 2015-09-22 22:24
@seanh not sure that's fixable, since it's probably UA / OS dependent. I don't know of any way to change the focus to the iframe, just set the focused within the frame. If the OS doesn't show a background window/frame as having focus, it may not be possible.

**Comment by edrex** [comment] 2015-09-22 22:34
Ah, I suspected there might be some iframe-related reason it worked this way. that's a bummer. It would be best if the focus could be set immediately. What is it that allows changing the focus on keystroke but not on create? Otherwise, maybe some class manipulation + style rule to visually highlight it (although that wouldn't help screen readers etc)?

**Comment by edrex** [comment] 2015-09-22 22:57
Tried to create a test case, but I'm not sure if I'm replicating the conditions for the extension correctly:

http://codepen.io/edrex/pen/dYpyov

**Comment by tilgovi** [comment] 2015-09-22 23:29
If I understand correctly, the focus is there, and at least the browser knows, and maybe directs the key events properly, but the OS might not and therefore the text area widget might not show the blinking beam cursor or whatever until you type or otherwise force the focus over there. I'm just speculating. If it has to do with the cursor style in a "background" window, that's not something I think we have any styling control over.

**Comment by nickstenning** [comment] 2016-04-20 01:53
Fixed by #3041.

**Closed by nickstenning** 2016-04-20 01:53 UTC
Labels: New Contributor Friendly, P3, Usability
