### ISSUE TITLE
Polyfill error w Firefox + Via on Github

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3185] opened 2016-04-07 14:34 UTC
### Steps to reproduce
1. Open Firefox 
2. Go to Github, perhaps here: https://via.hypothes.is/https://github.com/PatrickLouys/no-framework-tutorial/blob/master/06-dispatching-to-a-class.md#dispatching-to-a-class

### Expected behaviour
Sidebar should deploy

### Actual behaviour
Nothing

### Browser/system information
Recent FF

### Additional details
Console: "Error: Could not find module /h/static/scripts/polyfills.js"

**Comment by ajspadial** [comment] 2016-04-07 14:40
Firefox version 45.0.1
Same behaviour in Chrome Versión 49.0.2623.110 m

Note: OS (Windows 7)

**Comment by robertknight** [comment] 2016-04-07 15:35
I'm not able to reproduce the problem testing just now on the same URL. There is a different issue with GitHub + Via + Firefox (I see `e.toLowerCase is not a function`). I wonder if this was a temporary blip. Can you still reproduce the problem?

**Comment by dwhly** [comment] 2016-04-07 16:38
> testing just now on the same URL

With which Browser / OS combo?  On via?

It's still failing for me w/ gh + via + FF.  This was the original error... or am I misunderstanding you.

**Comment by nickstenning** [comment] 2016-04-20 00:47
Closing as a duplicate of #3027.

**Closed by nickstenning** 2016-04-20 00:47 UTC
