### ISSUE TITLE
Over eager z-index on site breaks annotation widget

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2720] opened 2015-11-12 15:25 UTC
This page uses a `z-index: 6000` on the `<section>` tag:
https://www.edo-tokyo-museum.or.jp/s-exhibition/special/3802/%E5%BE%B3%E5%B7%9D%E3%81%AE%E5%9F%8E%E3%80%80%EF%BD%9E%E5%A4%A9%E5%AE%88%E3%81%A8%E5%BE%A1%E6%AE%BF%EF%BD%9E%E5%B1%95/

As such, the annotation widget shows below the content in most places (except for the one spot where @tkanai found).

<img width="211" alt="2015-11-12 10_17_16-mail" src="https://cloud.githubusercontent.com/assets/43209/11122124/b193cd3c-8927-11e5-8f0b-894cc8062750.png">

**Comment by holtzermann17** [comment] 2015-12-01 14:31
This is related to (but not the same as) #2759.

**Comment by nickstenning** [comment] 2016-04-11 12:51
Closing this as a duplicate of #2869.

**Closed by nickstenning** 2016-04-11 12:52 UTC
Labels: P3, Web Page Compatibility
