### ISSUE TITLE
Several annotations seemingly made on 'local files' come up on search results

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/h#4185] opened 2016-12-07 16:22 UTC
### Steps to reproduce
1. Navigate to: https://hypothes.is/search?q=%22gold+star%22&page=5

### Expected behaviour
Uncertain

### Actual behaviour
I see several search results for 'local file' 'untitled' annotations.

### Browser/system information
Chrome

### Additional details
https://www.dropbox.com/s/8c7vhjo5b8t4jh3/Screenshot%202016-12-07%2011.18.03.png?dl=0

**Comment by dwhly** [comment] 2016-12-07 16:30
@judell: These are oddly arXiv trackbacks-- which *do* actually link to pages.  Maybe you can check it out.

**Comment by nickstenning** [comment] 2017-02-22 11:33
These are all annotations submitted programmatically by arXiv, and which don't contain any page metadata (which would include the page title).

We can't display a title if we don't have a title.

Closing as not a bug.

**Closed by nickstenning** 2017-02-22 11:33 UTC
Labels: Feature: Activity Pages
