### ISSUE TITLE
Mobile layout is broken on iOS Safari

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4057] opened 2016-11-11 20:02 UTC
It's fine when testing it on an iOS-sized device in Chrome dev tools, but on my real iPhone 5S the layout is broken:

![img_0630](https://cloud.githubusercontent.com/assets/22498/20228553/9ca1b442-a849-11e6-83b0-db5cf735033c.PNG)

**Comment by robertknight** [comment] 2016-11-12 13:05
Duplicate of https://github.com/hypothesis/h/issues/4048

**Closed by robertknight** 2016-11-12 13:05 UTC
Labels: Feature: Activity Pages
