### ISSUE TITLE
Client/stream sync: Threaded reply visible in browser, absent in stream

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2111] opened 2015-03-30 15:55 UTC
https://twitter.com/chronicallydave/status/581072276151496704

Dan's reply shows up here:

![hbug-askins-twitter-01](https://cloud.githubusercontent.com/assets/46509/6900308/8184596a-d6ba-11e4-8057-5556f3bdc299.jpg)

But not here:

![hbug-askins-twitter-02](https://cloud.githubusercontent.com/assets/46509/6900307/81804190-d6ba-11e4-810e-eb62cdb59aac.jpg)

**Comment by gergely-ujvari** [comment] 2015-03-30 16:04
It is not visible because the user of the reply is not 'judell' and the stream has the user:judell query, which filters the whole thread.

**Comment by tilgovi** [comment] 2015-03-30 17:26
Tempted to close since this is the expected behavior, but if @judell would like to amend the description we can turn this into a proposal for a change in search behavior.

**Comment by judell** [comment] 2015-03-30 18:04
Perhaps, but not yet, still wrapping my head around behaviors. 

I see that https://hypothes.is/a/B1Nd55a9SKSoF5J4GAc62w returns the unfiltered thread for the url https://twitter.com/chronicallydave/status/581072276151496704. 

I see also that this is not (yet) a thing:

https://hypothes.is/stream?q=url:[URL_ENCODED_TEXT]

(https://github.com/hypothesis/h/blob/cc25824fefa446cb265b78d95672c923b6aab4b1/h/views.py#L99)

I think it's fundamentally important for an url: query to be user-accessible on the stream. I'll make that proposal separately.

**Comment by tilgovi** [comment] 2015-03-30 18:07
The blob you linked to in views.py is about the /u/ and /t/ aliases for user and tag search, respectively. That is not the code for parsing these queries.

The supported syntax should be "uri:" but it doesn't appear to work for some reason.

**Comment by tilgovi** [comment] 2015-05-01 00:14
This is probably closed now with the change that disabled the thread filter on the stream.

**Comment by tilgovi** [comment] 2015-05-01 00:28
Closed by e139ca7272cba3c0fb3f3392bee4ac60e20e9d42

**Closed by tilgovi** 2015-05-01 00:28 UTC
