### ISSUE TITLE
Made some highlights, logged in, got my entire list of annotations in the sidebar

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2009] opened 2015-03-09 14:12 UTC
:astonished: 

Not sure if that's the only way to trigger that happening, but it's the first time I've seen it.

**Comment by RawKStar77** [comment] 2015-03-12 22:33
I'm not exactly sure what this bug is about. Could you clarify a bit more?

**Comment by BigBlueHat** [comment] 2015-03-13 13:45
By "entire list of annotations" I mean every annotation I've left on *any* resource...not just the one I'm viewing.

To reproduce:
 - open a web page to annotate
 - turn on Hypothes.is (I used the bookmarklet, but they should all be..nearly..the same)
 - make sure you're logged out (private browsing sessions are useful here)
 - turn on highlight mode
 - make some highlights
 - login
 - scroll up and down a bit to get the sidebar to load any non-visible content

Also...try toggling highlight mode on and off (after logging in) and you'll watch the cards collapse and refill...which is possibly a different :bug:.

**Comment by tilgovi** [comment] 2015-03-13 19:14
/me wonders if it's some race between login and search.

**Comment by tilgovi** [comment] 2015-03-13 19:14
or, rather, maybe we lose the page metadata at some point and don't properly filter the new search.

**Comment by tilgovi** [comment] 2015-05-11 20:25
Without more info, it's impossible to make progress here.

**Comment by BigBlueHat** [comment] 2015-05-29 19:29
k. This just happened again. This time on https://hypothes.is/blog/poynter-annotation-summit-at-the-new-york-times/

Made some a selection, started to annotate, realized I wasn't logged in, clicked login, logged in, sidebar (previously empty) reloaded with what seem to be loads of annotations from `http(s)://hypothes.is/` +/- query strings.

**Comment by BigBlueHat** [comment] 2015-05-29 19:34
Actually....it's doing it for that page anytime I open the sidebar post-login (not just immediately after).

Happened using both the extension in Chrome and the bookmarklet in Firefox.

Oh...and it seems the list of results is in at least a different order... :confused:

**Comment by tilgovi** [comment] 2015-05-29 21:24
Could this be: https://github.com/hypothesis/h/issues/2240

Known to affect our blog.

**Comment by tilgovi** [comment] 2015-05-29 21:24
If it's truly a separate bug you'll know it by seeing annotations that aren't anywhere on hypothes.is.

**Comment by judell** [comment] 2015-06-11 23:37
Tagged false_positives

**Comment by tilgovi** [comment] 2015-08-05 01:47
Closing as duplicate of #2240 until @BigBlueHat says otherwise.

**Closed by tilgovi** 2015-08-05 01:47 UTC
Labels: Bug, P2

**Comment by BigBlueHat** [comment] 2015-08-05 16:50
Yeah. I do think this was #2240 the first time I saw it. :stuck_out_tongue: 

Cheers!
