### ISSUE TITLE
Badge count differs for URL variants that anchor the same annotations

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3056] opened 2016-03-04 17:13 UTC
# Expected

Same badge count for http://www.nytimes.com/2015/10/11/opinion/sunday/what-really-keeps-women-out-of-tech.html and http://www.nytimes.com/2015/10/11/opinion/sunday/what-really-keeps-women-out-of-tech.html?_r0

# Actual

No badge count for the latter

**Comment by nickstenning** [comment] 2016-03-14 16:49
This is a duplicate of https://github.com/hypothesis/h/issues/2559, which was closed because this isn't a bug, it's a side-effect of how the badge is currently implemented. If we want to prioritise fixing this issue let's create a card for it.

**Closed by nickstenning** 2016-03-14 16:49 UTC
