### ISSUE TITLE
libsass and bourbon

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2201] opened 2015-04-30 02:22 UTC
Consider switching to libsass and bourbon instead of compass.
http://bourbon.io/
https://pypi.python.org/pypi/libsass/0.7.0

**Comment by keitheis** [comment] 2015-04-30 10:29
Autoprefixer might be another candidate to compass or bourbon.
https://github.com/postcss/autoprefixer
http://webassets.readthedocs.org/en/latest/builtin_filters.html#autoprefixer

**Comment by nickstenning** [comment] 2015-07-23 08:51
Closing as a dupe of #1292.

**Closed by nickstenning** 2015-07-23 08:51 UTC
Labels: New Contributor Friendly
