### ISSUE TITLE
Lack of Double deployment protection

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2015] opened 2015-03-10 16:06 UTC
Seen this locally in current master branch with bookmarklets and on prod, deploying the extension to pages where we have H embedded.

If you try to deploy the extension or the bookmarklet to a page which already has h, a second sidebar opens and in the console log you get only one exception:

```
Uncaught Error: A second Discovery server has been detected at http://0.0.0.0:5000.
This is unsupported and will cause unexpected behaviour.
```

We have to defend against second deployment attempts.

**Comment by csillag** [comment] 2015-03-10 16:51
Isn't this a duplicate of https://github.com/hypothesis/h/issues/1946 ?

**Comment by tilgovi** [comment] 2015-03-20 18:46
Closing as duplicate of #1688.

**Closed by tilgovi** 2015-03-20 18:46 UTC
Labels: Bug
