### ISSUE TITLE
stream search for tags should not use 'any'

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2940] opened 2016-02-10 17:10 UTC
Follow-on to https://github.com/hypothesis/h/issues/2153, in which we establish that the API query https://hypothes.is/api/search?tags=piga-1 now returns exactly one result for 'piga-1' instead of, as formerly, also results for 'piga' and '1'.

We should now expect the same result for:

https://hypothes.is/stream?q=tags:piga-1

Instead it returns many results. The API query issued by the client shows why:

https://hypothes.is/api/search?_separate_replies=true&any=tags%3Apiga-1&limit=20&offset=0

**Comment by nickstenning** [comment] 2016-02-10 17:32
Not a bug. The stream search facet is called `tag`, not `tags`, as demonstrated by the links to tag searches on annotation cards:

https://hypothes.is/stream?q=tag:%27piga-1%27

Closing.

**Closed by nickstenning** 2016-02-10 17:32 UTC
Labels: P2
