### ISSUE TITLE
Down arrow below bottom edge of window?

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#864] opened 2013-10-29 17:13 UTC
http://www9.georgetown.edu/faculty/jod/augustine/ddc4.html

**Comment by tilgovi** [comment] 2015-02-25 18:52
Still happens.

**Comment by judell** [comment] 2015-06-11 20:22
Not reproducible now because no annotations exist for either example. Close?

**Comment by tilgovi** [comment] 2015-06-11 21:42
Fine for me. Closing.

**Closed by tilgovi** 2015-06-11 21:42 UTC
Labels: Bug, Site Report
