### ISSUE TITLE
Saving annotation fails after h has been open for a long time.

### ISSUE THREAD

**Issue by jtremback** [hypothesis/h#2431] opened 2015-08-03 21:03 UTC
Several times now, coming back to a page I was annotating, I have found that a new annotation will not save:

![image](https://cloud.githubusercontent.com/assets/1335122/9047696/692f4852-39e8-11e5-93cf-8f036a529fdf.png)

**Comment by tilgovi** [comment] 2015-08-03 21:05
Duplicate of #1492

**Closed by tilgovi** 2015-08-03 21:05 UTC
