### ISSUE TITLE
Strange annotation counts

### ISSUE THREAD

**Issue by edsu** [hypothesis/h#2724] opened 2015-11-17 22:57 UTC
I'm annotating a page here:

http://firstmonday.org/ojs/index.php/fm/article/view/2484/2199

You can see in the hypothesis plugin icon indicates there are 33 annotations. But in fact there are only 4. The last of which doesn't appear to be an annotation on this page. But it is an annotation from the same host (firstmonday.org).

https://hypothes.is/a/zeuSLHWXQ8254aWAEA_njg

![screen shot 2015-11-17 at 5 54 26 pm](https://cloud.githubusercontent.com/assets/33829/11227553/9e6284ac-8d54-11e5-9ad7-0589d1b70fad.png)

**Comment by judell** [comment] 2015-11-18 01:46
The missing annotations are present in the response the client receives from its API request to the server. But they are not anchoring, so the question is: why not?

Here is one of those orphans:

```  
              {
                    "exact": "A 2010 study of 61 million voters published in Nature showed that a single Facebook social message from a friend noting \u201cI Voted\u201d increased voter turnout directly by about 60,000 voters and indirectly through social contagion by another 280,000 voters, for a total of 340,000 additional votes.",
                    "prefix": "\u2014 can have significant effects. ",
                    "type": "TextQuoteSelector",
                    "suffix": " The authors therefore argued th"
                }
```

The "exact" quote doesn't appear in the current version of the article. I haven't checked all of the orphans but assuming that's the pattern, the causes might be:

1. The article changed

2. The article was erroneously aliased to a different article

I can't check 1) easily but I can check 2). Here's one way. First, query the API:

https://hypothes.is/api/search?uri=http%3A%2F%2Ffirstmonday.org%2Fojs%2Findex.php%2Ffm%2Farticle%2Fview%2F2484%2F2199

Then scan the link: fields of the annotations for aliases. Here's one that appears often and doesn't look right:

http://firstmonday.org/ojs/index.php/fm/gateway/plugin/WebFeedGatewayPlugin/rss

That's an RSS feed that might have many different things in it.

curl http://firstmonday.org/ojs/index.php/fm/gateway/plugin/WebFeedGatewayPlugin/rss | grep "&lt;title>"

It does.

```
Why study technology non-use?
Lines of power: Availability to networks as a social phenomenon
Pulling the plug visually: Images of resistance to ICTs and connectivity
The gender-technology divide or perceptions of non-use?
Technologies of avoidance: The swear jar and the cell phone
The user as network
Smartphone resistance as media ambivalence
Exploring ethnographic techniques for ICT non-use research: An Amish case study
Entangled with technology: Engagement with Facebook among the young old
Replicants, imposters and the real deal: Issues of non-use and technology resistance in vintage and software instruments
```

Which in itself is not a problem because nobody was annotating the RSS feed. But if we now scan the API reponse for annotated URIs we get:

http://firstmonday.org/article/view/4961/3868
http://firstmonday.org/ojs/index.php/fm/article/view/2484/2199
http://firstmonday.org/ojs/index.php/fm/article/view/6169/4904

If each of those declares an equivalence to the feed than annotations for all land in the same bucket. And that's what these articles do:

&lt;link rel="alternate" type="application/rdf+xml" title="First Monday (rdf+xml)" href="http://firstmonday.org/ojs/index.php/fm/gateway/plugin/WebFeedGatewayPlugin/rss" />

**Comment by judell** [comment] 2015-11-19 17:18
Not a bug, so I'm closing this. Note that we have work scheduled to enable an authorized individual to remove wrong aliases from the database.

**Closed by judell** 2015-11-19 17:18 UTC

**Comment by edsu** [comment] 2015-11-19 17:33
Thanks for the analysis on this one @judell. I wonder if h should be more conservative in the resources it will link together as equivalent? Maybe it shouldn't say a page is equivalent to its feed?

**Comment by robertknight** [comment] 2015-11-19 17:38
@edsu - Agreed, in this case I think we could be smarter about handling RSS `<link>` tags and other variants as well. Our document equivalence handling is relatively simplistic at the moment, as resources permit, we'll want to improve it in a variety of directions in future.
