### ISSUE TITLE
inconsistent sync between highlight in document and annotation card in sidebar

### ISSUE THREAD

**Issue by balmas** [hypothesis/h#2707] opened 2015-11-02 13:37 UTC
Not sure if this is easily reproducible, but we noticed an interesting problem with a set of our student annotations on this page http://perseids.org/sites/smiths/A/artemis_1.html

The following 2 annotations done on this page both target the same word "Apollo":

https://hypothes.is/api/annotations/RpP38w5gRO-BuhmSgHVq2A
https://hypothes.is/api/annotations/gJ4nmXQmTru7CmkK0LpN_A

You'll note that the path to the endContainer and startContainer in the target fragmentSelector starts with div[3] in RpP38w5gRO-BuhmSgHVq2A  and div[2] in gJ4nmXQmTru7CmkK0LpN_A .  The latter is correct, and is the only one that appears highlighted on the page.  As the former was actually done more recently, I wonder if this is an indication of a newly introduced bug?

**Comment by tilgovi** [comment] 2015-11-02 20:11
I see that it's the same user that created both. The one with `div[3]` is newer than the one with `div[2]`. Is it possible that the user installed a browser extension (not Hypothesis) in between? Some extensions insert new elements into the page, which can change the path for the `RangeSelector`. This is one of the reasons Hypothesis uses multiple representations of the selection.

So, I would not jump to conclusions about the selector having a bug. However, that only one of the Annotations shows does seem to be a bug in the highlighter or the anchoring code in Hypothesis. I would focus on that.

**Comment by judell** [comment] 2015-11-02 21:42
I just encountered a similar thing at http://www.newyorker.com/science/maria-konnikova/being-a-better-online-reader.

Here is a selector from annotation A made today:

```
       "selector": [
                {
                    "conformsTo": "https://tools.ietf.org/html/rfc3236",
                    "type": "FragmentSelector",
                    "value": "articleBody"
                },
                {
                    "endContainer": "/div[2]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]",
                    "endOffset": 620,
                    "type": "RangeSelector",
                    "startOffset": 620,
                    "startContainer": "/div[2]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]"
                },
                {
                    "start": 11660,
                    "end": 11779,
                    "type": "TextPositionSelector"
                },
                {
                    "exact": "If the online readers took notes on paper, however, the negative effects of Internet access were significantly reduced.",
                    "prefix": " Internet-enabled counterparts. ",
                    "type": "TextQuoteSelector",
                    "suffix": " It wasn\u2019t the screen that disru"
                }
            ],
   ```

And one from annotation B made in September:

```
           "selector": [
                {
                    "conformsTo": "https://tools.ietf.org/html/rfc3236",
                    "type": "FragmentSelector",
                    "value": "articleBody"
                },
                {
                    "endContainer": "/div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]",
                    "endOffset": 620,
                    "type": "RangeSelector",
                    "startOffset": 501,
                    "startContainer": "/div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]"
                },
                {
                    "start": 12169,
                    "end": 12288,
                    "type": "TextPositionSelector"
                },
                {
                    "exact": "If the online readers took notes on paper, however, the negative effects of Internet access were significantly reduced.",
                    "prefix": " Internet-enabled counterparts. ",
                    "type": "TextQuoteSelector",
                    "suffix": " It wasn\u2019t the screen that disru"
                }
            ],
```

Both anchor at an appropriate location in the sidebar. However only in the case of B is there document/sidebar synchronization, by which I mean:

1. Clicking the highlight focuses on an annotation the sidebar
2. Clicking the annotation in the sidebar scrolls to and emphasizes the highlight

**Comment by tilgovi** [comment] 2015-11-02 22:11
Here's something to test if you control these annotations:

- Make one private
- Load Hypothesis in a private browsing context or log out so that only one appears
- Repeat with the public/private inverted

In other words, check whether the selector difference is the reason it doesn't appear to anchor.

**Comment by tilgovi** [comment] 2015-11-02 22:13
If they both successfully create a highlight when the other one is private and not accessible then ignore the selector difference (which can be caused by any number of browser differences or intervening markup changes) and please just report the bug that identical highlights sometimes stomp on each other.

**Comment by judell** [comment] 2015-11-03 20:13
I created my own annotation for that same selection. So now:

1 . https://hypothes.is/api/annotations/6gnz46YrSTKuWGlrH3Xr6g 

    Created by CalamityWrites on Sep 02

    /div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]

2. https://hypothes.is/api/annotations/ix0puzkETtGiZliStKku6w

    Created by jocelyncart on Nov 2

    /div[2]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]"

3. https://hypothes.is/api/annotations/4whka2S-SfSsO-FxZS9Esw

   Created by judell on Nov 3

   /div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]

Of these, the ones that show up in the sidebar when clicking the selection (and that scroll the doc to the selection when clicked in the sidebar) are [1, 3].  Coincidentally or not, they share a common selector different from [2].

**Comment by judell** [comment] 2015-11-03 20:13
I created my own annotation for that same selection. So now:

1 . https://hypothes.is/api/annotations/6gnz46YrSTKuWGlrH3Xr6g 

    Created by CalamityWrites on Sep 02

    /div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]

2. https://hypothes.is/api/annotations/ix0puzkETtGiZliStKku6w

    Created by jocelyncart on Nov 2

    /div[2]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]"

3. https://hypothes.is/api/annotations/4whka2S-SfSsO-FxZS9Esw

   Created by judell on Nov 3

   /div[3]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]

Of these, the ones that show up in the sidebar when clicking the selection (and that scroll the doc to the selection when clicked in the sidebar) are [1, 3].  Coincidentally or not, they share a common selector different from [2].

**Comment by tilgovi** [comment] 2015-11-03 21:32
If I select some of the same text right now, I see `/div[1]/div[3]/div[2]/article[1]/div[1]/div[1]/div[1]/p[11]` which is accurate for the DOM in my browsing window.

**Comment by tilgovi** [comment] 2015-11-03 21:37
The perseids.org case is more interesting because the site is very static. The New Yorker is probably not a good test here since it's possible it has different views for mobile/desktop, subscriber/not, A/B tests of features, changing ad units, etc. In other words, many of the various things that we encounter on the web that make changes in the XPath expected and motivate the use of other selector implementations.

These are less likely to have occurs on perseids, though not impossible. Anyway, knowing the code for this very well it's highly unlikely that there's a bug in the XPath generation. That code is pretty trivial and very deterministic.

Again, it's really important to separate these issues, though, and focus on why some annotations anchor and others do not. Someone wishing to debug this should run a private h instance and copy some of the annotations into it. See which succeed and which fail. See if any succeed in isolation but fail in the presence of others. See if you can reproduce and explain.

**Comment by tilgovi** [comment] 2015-11-03 21:47
There are two things being discussed here:

1. XPath container paths for what appears to be the same selection appear to be sometimes different.
2. Multiple annotations which share common selectors appear to anchor inconsistently.

We don't know if (1) is a bug or just normal deviations. We don't know why (2) is occurring, and in particular if (1) is a cause.

We should separate the issues and investigate. As it stands right now, the issue is describes only (1) and assumes a bug where there may not be one and (2) is buried in the comments.

Recommended triage steps:

- Close this issue
- Open an issue on tilgovi/xpath-range or tilgovi/simple-xpath-position to prompt an investigation into whether (1) is a possible bug
- Open an issue for (2) here to investigate whether there are problems with overlapping anchors, if no such issue exists already

**Comment by balmas** [comment] 2015-11-03 22:09
I would have liked to help debug as suggested with the annotations in the initial report but I am not the owner...

**Comment by tilgovi** [comment] 2015-11-03 22:10
No worries, @balmas! I'm not complaining, just trying to route.

**Comment by judell** [comment] 2015-11-03 22:37
I'm all for separating concerns but at this point I'm seeing a strong correlation. In the Perseids article, these three annotations exactly match the pattern I found above for the NYTimes article.

1. https://hypothes.is/api/annotations/gJ4nmXQmTru7CmkK0LpN_A

/div[2]/section[1]/div[1]/p[1]

2. https://hypothes.is/api/annotations/RpP38w5gRO-BuhmSgHVq2A

/div[3]/section[1]/div[1]/p[1]

3. https://hypothes.is/api/annotations/vdk8AxjfQ5in579QnlUvCA

/div[2]/section[1]/div[1]/p[1]

The exact same statement from above applies here too:

"Of these, the ones that show up in the sidebar when clicking the selection (and that scroll the doc to the selection when clicked in the sidebar) are [1, 3]. Coincidentally or not, they share a common selector different from [2]."

**Comment by tilgovi** [comment] 2015-11-03 22:40
Sure, but even *if* there are two bugs *and* they are causally linked, they still constitute two separate bugs and it may be possible to reproduce each independently or together.

It is not a requirement that all selectors succeed, only that one succeeds. If the annotation fails to anchor that's distinct from whether it also has an incorrect XPath selector.

**Comment by judell** [comment] 2015-11-03 22:48
It may help, btw, to clarify what we mean by _fails to anchor_.

I have used that phrase to mean: _was returned by the client's api query but is not visible in the sidebar after page load_.

That meaning does not apply in either of these examples. The annotations anchor, but some behave differently to other w/respect to what I have sometimes called _crossframe synchronization_ as a shorthand for _if you click a card in the sidebar, the document scrolls to its annotation, and conversely if you click that annotation's highlight in the doc, the sidebar focuses on that card plus others that share the same selection_.

**Comment by tilgovi** [comment] 2015-11-03 22:52
In the perseids example, there are only two highlights (originally one, but now that you've added a third one, two) when there should be three (originally two).

**Comment by judell** [comment] 2015-11-19 18:13
Retitled.

**Comment by tilgovi** [comment] 2015-11-19 18:54
I don't understand the new title. Are you saying a highlight is missing but the card is present and not marked as an orphan?

**Comment by nickstenning** [comment] 2016-02-10 14:39
This is getting very confusing.

Closing in favour of a clearer restatement of the problem: https://github.com/hypothesis/h/issues/2934.

**Closed by nickstenning** 2016-02-10 14:39 UTC
Labels: Bug, P3
