### ISSUE TITLE
Strategy 'two-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2013] opened 2015-03-10 14:31 UTC
Seen with Prod extension v0.3.2.1724

To reproduce:
1. Open https://en.wikipedia.org/wiki/Main_Page
2. Activate our extension on the page
3. Check console logs

Result:
```
 Strategy 'two-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined
    at new DTM_DMPMatcher (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:6:21900)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.ensureDMP (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:31587)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.searchFuzzyWithContext (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:27224)
    at FuzzyTextAnchors.Annotator.Plugin.FuzzyTextAnchors.FuzzyTextAnchors.twoPhaseFuzzyMatching (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:5094)
    at EnhancedAnchoring.bind (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:3052)
    at EnhancedAnchoring.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.createAnchor (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31418)
    at Host.Annotator.setupAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:10053)
    at Annotator.loadAnnotations.loader (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25188)
    at Host.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25368)
    at Host.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.pluginInit.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31086)
hypothesis.min.js?5750b1df:1 Strategy 'one-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined
    at new DTM_DMPMatcher (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:6:21900)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.ensureDMP (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:31587)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.searchFuzzy (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:26334)
    at FuzzyTextAnchors.Annotator.Plugin.FuzzyTextAnchors.FuzzyTextAnchors.fuzzyMatching (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:6244)
    at EnhancedAnchoring.bind (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:3052)
    at EnhancedAnchoring.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.createAnchor (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31418)
    at Host.Annotator.setupAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:10053)
    at Annotator.loadAnnotations.loader (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25188)
    at Host.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25368)
    at Host.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.pluginInit.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31086)
```

**Comment by csillag** [comment] 2015-03-10 14:32
It looks like the "diff-match-patch" library is simply not shipped with the extension.

**Comment by csillag** [comment] 2015-03-10 14:32
I am marking this as a blocker.

**Comment by csillag** [comment] 2015-03-10 16:42
> It looks like the "diff-match-patch" library is simply not shipped with the extension.

It's not only the extension; it's simply not bundled at all with our assets. (Impacts the bookmarklet, too.)

**Comment by csillag** [comment] 2015-03-10 16:52
See PR #2018 for the fix.

Shall we create a card somewhere to add automatic tests for avoiding these kind of regressions?

**Closed** 2015-03-11 06:13 UTC
Labels: Blocker, Bug
