### ISSUE TITLE
Improve welcome / help page

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/h#2206] opened 2015-04-30 21:58 UTC
This issue was inspired by @jeremydean. We should continue to work to improve the [help page](https://hypothes.is/docs/help) as it is still a sub-par getting started experience.

Ideas are welcome (especially suggestions for improving the copy), but regardless we should update it so that it covers the mobile annotation creation workflow, contains helpful links to perhaps the category of our blog that documents features like local PDF annotation, and covers sharing annotations.

I also think some GIFs might be extremely helpful.

**Comment by tilgovi** [comment] 2015-04-30 22:10
Could you articulate something more concrete that will let us know when this issue has been delivered?

**Comment by RawKStar77** [comment] 2015-04-30 22:40
> Could you articulate something more concrete that will let us know when this issue has been delivered?

Here's my attempt at a more concrete list:

- [ ] Link to Chrome extension and bookmarklet: It is not too hard to link to them on the help page. 
- [ ] "If you wish to install Hypothesis on your own site then head over to GitHub." Should include a relevant link.
- [ ] Cover mobile annotation creation workflow: there is no popup so we should explicitly state what people are supposed to do.
- [ ] Link to relevant blog categories.

Any others?

**Comment by RawKStar77** [comment] 2015-04-30 22:41
> Link to Chrome extension and bookmarklet

I think this is important because people might first experience the app embedded on a page or by following a via link.

**Comment by RawKStar77** [comment] 2015-04-30 22:47
We should also resolve this styling issue:
![styling issue](https://cloud.githubusercontent.com/assets/521978/7423932/31ccd79a-ef50-11e4-84e6-69a5b91f9ad3.png)

**Comment by dwhly** [comment] 2015-04-30 22:51
> Resolve the following styling issue:

I can't see what the issue is...

**Comment by tilgovi** [comment] 2015-05-01 00:52
Looking good.

**Comment by nickstenning** [comment] 2016-02-10 13:15
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Closed by nickstenning** 2016-02-10 13:15 UTC
Labels: Documentation, Usability
