### ISSUE TITLE
Stream sort dropdown corrupted when extension loaded

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#1765] opened 2014-12-04 16:33 UTC
### Steps to reproduce

1. Go to https://hypothes.is/stream
2. Load the extension
3. Change the sort order of the stream

### Expected behaviour

Sort dropdown reflects new sort order.

### Observed behaviour

Sort dropdown text duplicated:

![screen shot 2014-12-04 at 17 26 42](https://cloud.githubusercontent.com/assets/3602/5301761/9e968c2e-7bdb-11e4-9507-325f5f46cbca.png)

**Comment by gergely-ujvari** [comment] 2015-01-07 10:43
The source of the bug is our invasive highlight technique.

Originally the structure of the sort-dropdown looks like this:
```
<span role="button" class="dropdown-toggle ng-binding" data-toggle="dropdown">
        Sorted by newest
        <i class="h-icon-triangle small"></i>
      </span>
```
But after loading the extension it looks like this:
```
<span role="button" class="dropdown-toggle ng-binding" data-toggle="dropdown">
        <span class="annotator-hl">Sorted by newest
        </span>        
        <i class="h-icon-triangle small"></i>
</span>
```

And changing the ordering transforms it to this:
```
<span role="button" class="dropdown-toggle ng-binding" data-toggle="dropdown">
        Sorted by oldest
        <span class="annotator-hl">Sorted by newest
        </span> 
        <i class="h-icon-triangle small"></i>
</span>
```

Basically, the control mechanism for our sort dropdown cannot recognize the highlighted text as the one it should remove, so it assumes that no sorting is selected and inserts the new sorting text.

This issue is not limited to our stream page, it can occur in every web-page, our dom-manipulation for highlights can break anything.

So, only a workaround can be to disallow loading the extension in our stream-page.
The long way solution must be introducing a less invasive highlight technique.

**Comment by csillag** [comment] 2015-01-08 16:55
> So, only a workaround can be to disallow loading the extension in our stream-page.

We can also simply forbid annotating our own UI elements.

In fact Annotator already has a feature for that: we don't allow annotating anything with an `annotator-<whatever>` class. We could extend that support to also protect `hypothesis-<whatever>` elements, and then we only have to apply those classes to all important elements to our UI.

**Comment by tilgovi** [comment] 2015-01-08 18:15
I vote to simply close this.

**Comment by csillag** [comment] 2015-01-08 18:40
@dwhly  wrote:

> Can we delete this annotation

Yes, of course we can.... thought I'm not sure who has the right permission to do that.

**Comment by judell** [comment] 2015-06-11 22:59
Does not reproduce in 4.1.139.

**Closed by judell** 2015-06-11 22:59 UTC
Labels: 0 - Uncategorized, Bug
