### ISSUE TITLE
some annotations awol for http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2712] opened 2015-11-02 17:56 UTC
Expected: An annotation anchored to the title 2014 Breaks Heat Record

Actual: Not there

Historical background: two version of this URL have been in play:

1. http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html

2. http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html?_r=0

Queries:

badge and api:

http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html -> 13
vs.
http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html?_r=0 -> 18

(the _r=0 result includes the missing annotation)

client: 

in both cases, it calls https://hypothes.is/api/search?group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http%3A%2F%2Fwww.nytimes.com%2F2015%2F01%2F17%2Fscience%2Fearth%2F2014-was-hottest-year-on-record-surpassing-2010.html and gets back only 13 annotations

PS: The client throws this JS error:

Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <img</a> src="http://ipccar5summary.org/wp-content/uploads/2014/10/WGI_FSPM1b_Observed-change-in-surface-temperature-1901%E2%80%932012.png" alt="Image Description" /></p>

I'm guessing that's unrelated and if confirmed I'll move this observation to another issue.

**Comment by judell** [comment] 2015-11-19 18:08
More data:

```
a = ["0D8-iNgrQIuABwPgekbKgw","4o88tpDqRDCWXGVb7Pkojw","7YkfxhpkSXmsBch3qgdwqQ","8XHAL1kvS7mlZohTSMqq9A","C87fUMJ9RaGJxtVxQtl3Zw","D1ghmLjqSdmVk2Im1DI4TQ","dtyOmHJYRNWoBMILTTMC2w","EcB6VQXrSKesjACAKaUk6A","GbfGSMVQQsmT2Dj-c0krlQ","pXXFzTZBRY-uooNKpqhUNw","Ru_PkLKYSKm0aOA8t3nC4g","tIyLiISNS9ibjTeJlhva2A","XQ2wdnp6SDanshof9m2Mzw"]

b = ["0D8-iNgrQIuABwPgekbKgw","4o88tpDqRDCWXGVb7Pkojw","7YkfxhpkSXmsBch3qgdwqQ","80l5wgMBS-6l4UWHF6MP1g","8XHAL1kvS7mlZohTSMqq9A","C87fUMJ9RaGJxtVxQtl3Zw","D1ghmLjqSdmVk2Im1DI4TQ","dtyOmHJYRNWoBMILTTMC2w","EcB6VQXrSKesjACAKaUk6A","G6wrNVr1TxuVCb8aGI0yEQ","GbfGSMVQQsmT2Dj-c0krlQ","pECNrdzdQVCH3snSaHXDLA","pXXFzTZBRY-uooNKpqhUNw","Ru_PkLKYSKm0aOA8t3nC4g","tIyLiISNS9ibjTeJlhva2A","vKP7oJF_SZKETgYG3anNLQ","WbHa75EfTKe60lo8iyPtTg","XQ2wdnp6SDanshof9m2Mzw"]

a = set(a)
b = set(b)
a - b
set([])
b - a
set(['G6wrNVr1TxuVCb8aGI0yEQ', 'pECNrdzdQVCH3snSaHXDLA', 'WbHa75EfTKe60lo8iyPtTg', '80l5wgMBS-6l4UWHF6MP1g', 'vKP7oJF_SZKETgYG3anNLQ'])
```

**Comment by nickstenning** [comment] 2016-02-10 14:52
13 vs 18 is because `http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html` is marked as URL known to be canonical. As discussed in #2652 we don't expand the search in such cases to all other known URIs. This isn't necessarily ideal behaviour but it's not a bug.

I've opened #2935 to track the sanitizer error.

**Closed by nickstenning** 2016-02-10 14:52 UTC
Labels: Bug, P3
