### ISSUE TITLE
Via proxy failing on Chrome iOS

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3267] opened 2016-05-02 20:13 UTC
### Steps to reproduce
1. Go to Chrome on iOS
2. Browse to https://via.hypothes.is/http://example.com/

### Expected behaviour
Proxied page should open

### Actual behaviour
Alert shows:  Warning: Something's not right here. Chrome is unable to verify that the URL for this site is correct:

### Browser/system information
Chrome 46 on iOS 9.3.1

### Additional details
Screenshots attached.

![img_0802 2](https://cloud.githubusercontent.com/assets/1413074/14966504/9f6b2ef8-1067-11e6-8f8a-0aaebef5ed71.PNG)

![img_0803 2](https://cloud.githubusercontent.com/assets/1413074/14966509/a7761a9a-1067-11e6-83c1-6bb257c62f71.PNG)

**Comment by nickstenning** [comment] 2016-07-22 14:45
I can't reproduce this any more. Closing.

**Closed by nickstenning** 2016-07-22 14:45 UTC
