### ISSUE TITLE
Problem with permissions (?)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2023] opened 2015-03-11 08:12 UTC
As reported by a user:

> When i replied to a comment that was already replied to, i couldn't edit my reply.

**Comment by raziellight** [comment] 2015-03-11 16:13
windows 7
latest version of chrome Version 41.0.2272.89 m
https://via.hypothes.is/static/ann/viewer/web/viewer.html?file=/h/id_/http://project.hypothes.is/design/page_vs_interpage_groups/page_vs_interpage_groups.pdf
at the bottom of the page at the questions section

"raz
Page-based groups seem like the logical next step. I am still-finding the concept of inter page groups fuzzy."
can't see options to edit

**Comment by dwhly** [comment] 2015-03-11 16:15
Raz, I'm not seeing your annotation.  It may not have gotten saved to the backend.  Can you reload the page and confirm that you're signed in?  Perhaps try to remake the annotation?

**Comment by raziellight** [comment] 2015-03-11 16:20
I think that's the case, because when i tried to log out it said two unsaved replies. I don't know how to save them, though. It's a little confusing because it looks like i've replied.

**Comment by dwhly** [comment] 2015-03-11 16:22
Hmm... can you try killing the tab and retrying?  This sounds like a corner case, race condition.  Any specific instructions on how to reproduce are very welcome.

**Comment by raziellight** [comment] 2015-03-11 16:30
when i went to http://project.hypothes.is/design/page_vs_interpage_groups/page_vs_interpage_groups.pdf the comments have disappeared. I'm not sure how to reproduce, but it seems that they weren't saved, so it was very confusing. And there was no option saying i could save it, just the posted comment without edit or save options or anything.
On a side note the hypothe.is buttons cover up the scrollbar, so i can't scroll. I had to mousewheel down.

**Comment by dwhly** [comment] 2015-03-11 16:32
Can you create a comment now?  In other words was this a corner case, or is the app broken here for you now?  I can make annotations that save on this page.

**Comment by raziellight** [comment] 2015-03-11 16:35
Ok i've tried to reply again, and it worked this time. Before i made that comment that didn't get saved, i made 3 other comments. Somehow it went from getting saved to not getting saved(but posted so it looked like it was saved). Not sure how that happened.

**Comment by csillag** [comment] 2015-03-11 17:28
I think this is probably the same thing as https://github.com/hypothesis/h/issues/1982. (No idea of the root cause, yet.)

One should reproduce it with a locally running server instance, in order to expect the server console output. (Not sure if it has anything to do with being a PDF, either.)

**Comment by raziellight** [comment] 2015-03-12 12:32
In this case i did create an annotation, and it did appear like i had created it, but It wasn't saved, and i had no edit/delete buttons.

**Comment by csillag** [comment] 2015-03-12 12:34
Most likely, that means that you haven't *actually* created it.
The server has most likely returned a "permission denied" message to 
the client, which didn't know how to handle it, ended up in the 
inconsistent state, and that caused that there were no edit and delete 
buttons.

**Comment by tilgovi** [comment] 2015-05-11 21:45
We have an open PR for adding notification when saving fails. I'm closing this issue since it's hard to know what went wrong.

**Closed by tilgovi** 2015-05-11 21:45 UTC
Labels: Bug
