### ISSUE TITLE
annotation not in expected location order

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2868] opened 2016-01-15 20:15 UTC
I'd expect the annotation that's highlighted, and focused in the sidebar, to be at the top, because the sidebar is set to Location order. Instead it appears in the middle of the sidebar. 

![image](https://cloud.githubusercontent.com/assets/46509/12363968/bcff488c-bb80-11e5-9e44-79ec82e5b599.png)

That happens because the annotation's start value does, indeed, place it somewhere in the middle. Here's a picture of the annotations ordered by start value:

![image](https://cloud.githubusercontent.com/assets/46509/12364082/734bfbe4-bb81-11e5-9bb6-e8627a65a5cf.png)

The two annotations connected to the selection "Is the University of Wisconsin-Madison a patent troll?" have start values of 12711 and 13090. Why?

**Comment by nickstenning** [comment] 2016-04-20 02:55
Without details of the annotation or URL this isn't reproducible. Closing.

**Comment by judell** [comment] 2016-04-20 14:26
At: http://www.nytimes.com/2015/10/24/opinion/the-patent-troll-smokescreen.html?_r=0

The following appear 1, 2 in the doc, 2, 1 in the sidebar.

https://hyp.is/AVI3AAy28sFu_DXLVbLQ/www.nytimes.com/2015/10/24/opinion/the-patent-troll-smokescreen.html

https://hyp.is/AVIthELH8sFu_DXLVZl7/www.nytimes.com/2015/10/24/opinion/the-patent-troll-smokescreen.htmlhttp://www.nytimes.com/2015/10/24/opinion/the-patent-troll-smokescreen.html?_r=0

**Comment by robertknight** [comment] 2016-05-30 07:24
Sorting of annotations in the sidebar is done based on the stored start and end positions of the `TextPositionSelector` selector. The annotation of the text "Is the University of Wisconsin-Madison a patent troll" does not show up at the top of the list in location order because it has a larger start offset for its TextPositionSelector (see https://hypothes.is/api/annotations/AVIlMa9V8sFu_DXLVY_y ) than the annotations which follow.

When I created a new annotation of the same text just now, it had a much lower start offset than the stored value.

One potential way we could fix this would be to calculate the `TextPositionSelector` to annotations after they are anchored in the page and use those instead of the offsets originally stored with the annotation. Whether this is feasible or not depends on how expensive it is to calculate the position offset.

**Comment by nickstenning** [comment] 2017-02-21 13:33
Moved to https://github.com/hypothesis/client/issues/248.

**Closed by nickstenning** 2017-02-21 13:33 UTC
Labels: P3
