### ISSUE TITLE
annotations not found by api uri query using chrome

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2486] opened 2015-09-04 19:17 UTC
URL: http://jonudell.net/udell/2006-09-20-turk-work.html

I created 3 annotations which are found by this query:

https://hypothes.is/api/search?user=judell

But not by this query:

https://hypothes.is/api/search?uri=http://jonudell.net/udell/2006-09-20-turk-work.html

**Comment by tilgovi** [comment] 2015-09-04 19:50
Duplicate of #2484

**Comment by judell** [comment] 2015-09-04 21:28
This is weirder than I realized.

For https://hypothes.is/api/search?uri=http://jonudell.net/udell/2006-09-20-turk-work.html, in Firefox, or using curl, I get 3 annotations.

{"rows": [{"updated": "2015-09-04T18:25:59.245759+00:00", "target": [], "tags": [], "text": "second reply", "created": "2015-09-04T18:25:59.245747+00:00", "uri": "http://jonudell.net/udell/2006-09-20-turk-work.html", "references": ["dUbMEypaSoCYHrfkkQcG5A", "narxRgZURhWN5FZbqtlWVA"], "user": "acct:judell@hypothes.is", "document": {"eprints": {}, "title": "Jon Udell / 2006/09/20 / Turk work", "twitter": {}, "dc": {}, "prism": {}, "highwire": {}, "facebook": {}, "link": [{"href": "http://jonudell.net/udell/2006-09-20-turk-work.html"}]}, "consumer": "00000000-0000-0000-0000-000000000000", "id": "t-quEdQoTRegTFTDCcX4fg", "permissions": {"admin": ["acct:judell@hypothes.is"], "read": ["group:__world__"], "update": ["acct:judell@hypothes.is"], "delete": ["acct:judell@hypothes.is"]}}, {"updated": "2015-09-04T18:25:52.363276+00:00", "target": [], "tags": [], "text": "first reply", "created": "2015-09-04T18:25:52.363264+00:00", "uri": "http://jonudell.net/udell/2006-09-20-turk-work.html", "references": ["dUbMEypaSoCYHrfkkQcG5A"], "user": "acct:judell@hypothes.is", "document": {"eprints": {}, "title": "Jon Udell / 2006/09/20 / Turk work", "twitter": {}, "dc": {}, "prism": {}, "highwire": {}, "facebook": {}, "link": [{"href": "http://jonudell.net/udell/2006-09-20-turk-work.html"}]}, "consumer": "00000000-0000-0000-0000-000000000000", "id": "narxRgZURhWN5FZbqtlWVA", "permissions": {"admin": ["acct:judell@hypothes.is"], "read": ["group:__world__"], "update": ["acct:judell@hypothes.is"], "delete": ["acct:judell@hypothes.is"]}}, {"updated": "2015-09-04T18:25:44.934974+00:00", "target": [], "tags": [], "text": "top-level annotation", "created": "2015-09-04T18:25:44.934961+00:00", "uri": "http://jonudell.net/udell/2006-09-20-turk-work.html", "user": "acct:judell@hypothes.is", "document": {"eprints": {}, "title": "Jon Udell / 2006/09/20 / Turk work", "twitter": {}, "dc": {}, "prism": {}, "highwire": {}, "facebook": {}, "link": [{"href": "http://jonudell.net/udell/2006-09-20-turk-work.html"}]}, "consumer": "00000000-0000-0000-0000-000000000000", "id": "dUbMEypaSoCYHrfkkQcG5A", "permissions": {"admin": ["acct:judell@hypothes.is"], "read": ["group:__world__"], "update": ["acct:judell@hypothes.is"], "delete": ["acct:judell@hypothes.is"]}}], "total": 3}

In Chrome, on two different machines, I get:

{"rows": [], "total": 0}

WTF?

**Comment by tilgovi** [comment] 2015-09-04 21:42
This is affected by the search_normalized feature flag and so browser doesn't matter but whether you're logged in as judell does.

**Closed by tilgovi** 2015-09-04 21:42 UTC

**Comment by judell** [comment] 2015-09-04 22:31
OK, thanks. I had thought search_normalized was turned off for everybody but evidently not.
