### ISSUE TITLE
Remove via proxy from the saved annotation uri

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2147] opened 2015-04-08 18:46 UTC
Take a look at this annotation: https://hypothes.is/api/annotations/u10seIqZQbeJ0tWm2YcItw
This was created via via.hypothes.is and the uri looks like the following: 
`"uri": "https://via.hypothes.is/h/http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/"`

IMO we should try to preserve the original uri when we create annotations using via.

**Comment by judell** [comment] 2015-04-08 20:55
I have noticed this and agree. We seem to unify these things in the backend but I would rather not enshrine via in this way. Low-pri for now but thanks for dropping a placeholder.

**Comment by tilgovi** [comment] 2015-04-08 21:02
Duplicate of #2062 I think.

**Closed by tilgovi** 2015-04-08 21:02 UTC
Labels: Enhancement
