### ISSUE TITLE
Icon + text off center in adder

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3135] opened 2016-03-23 20:39 UTC
The icon/label in the adder buttons appears shifted a bit high.

The top margin is ~8 pixels and the bottom margin on the Annotate button is ~12 pixels.  Part of what's happening is that the margin calculation (probably) takes into account the label on the 2nd button as well, where the descenders on the 'g's from "Highlight" hang lower.

Visually, the eye is drawn towards the first (left) button, and the center of mass appears off as a result.

Suggestion: Consider making the margins based on the baseline instead of the descender line of the button labels.  

![screenshot 2016-03-23 15 24 08](https://cloud.githubusercontent.com/assets/1413074/14002983/b505a380-f10c-11e5-9eca-b3ed8f1e6a42.png)

**Comment by nickstenning** [comment] 2016-03-29 09:55
Sorry, but I'm going to close this. It's not a bug. If you have feedback on the design of the adder, I'd suggest bringing that up in the design channel on Slack.

**Closed by nickstenning** 2016-03-29 09:55 UTC
