### ISSUE TITLE
Hypothesis not properly unloaded when de-activating extension

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3294] opened 2016-05-08 23:27 UTC
### Steps to reproduce
1. Activate H extension on page
2. Create an annotation
3. De-activate H extension
4. Re-activate H extension on same page

### Expected behaviour
After step 4, annotations should appear on the page in the same state as after step 2.

### Actual behaviour
After step 4, all the annotated sections of the page are covered with two highlights instead of just one.

### Additional details
Logging the calls to `Delegator#subscribe()` and `Delegator#unsubscribe()` shows that when annotator is loaded, it subscribes to these events on `document.body` which are not unsubscribed when deactivating the extension:

'beforeAnnotationCreated',  'annotationCreated', 'annotationUpdated', 'annotationsLoaded', 'annotationsUnloaded', 'annotationDeleted', 'panelReady', 'setVisibleHighlights'

Consequently, when H is activated a second time and annotations are loaded, both the old and new instances of H handle the events and the result is that two sets of highlights get created.

**Comment by nickstenning** [comment] 2016-05-12 11:28
This is a dupe of #3096.

**Comment by nickstenning** [comment] 2016-05-12 11:28
Feel free to move the details here to that issue and then close this one.

**Comment by nickstenning** [comment] 2016-05-16 07:41
Closing as a duplicate. I've copied the details here into a comment on the older issue.

**Closed by nickstenning** 2016-05-16 07:41 UTC
